### ISSUE TITLE
Grid view in recording backend

### ISSUE THREAD

**Issue by schefi** [nextcloud/spreed#10060]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
When Talked was a separate module there was a boolean option to select grid_mode for the recording instead of the speaker mode. Ever since the recording backend was integrated into Spreed this option is no longer available and recorded videos always show the person speaking at the moment.

**Describe the solution you'd like**
Introduce a configurable option in recording/server.conf to enforce grid view for the recorded video file.

**Describe alternatives you've considered**
I'm wondering if this is posible by passing an additional argument to the chromium or firefox browser internally started by the recording server.

**Comment by danxuliu** [comment]
This would be a recording UI customization, which is tracked in https://github.com/nextcloud/spreed/issues/8768

Until that is properly implemented there is a small hack that you could use: change to grid view after joining the call in the browser that performs the recording. To do that you would need to modify _nextcloud/talk/recording/Participant.py_ in the recording server and replace https://github.com/nextcloud/spreed/blob/5acf17d2f2e3e71d1572cad7020fc00a76c13491/recording/src/nextcloud/talk/recording/Participant.py#L526 with:
```
            store.commit('isGrid', true)
        ''')
```

After restarting the recording server all the calls will be recorded in grid view.

Nevertheless, please note that the grid may look strange in some cases (for example, if there are only two participants in the call) due to the participant for the recording server being hidden from the grid, but still occupying its place there :shrug: That will be of course addressed once the recording UI can be customized :-)
