### ISSUE TITLE
Conversation item border is cut of when tabbing

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10443]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Click into the search and tab into the conversation list

### Expected behaviour
Border around the conversation

### Actual behaviour
is cut off:
![grafik](https://github.com/nextcloud/spreed/assets/213943/15fd8359-3bc2-4141-8d71-b7fd31138098)

## Talk app

**Talk app version:**stable27

**Comment by nickvergessen** [comment]
cc @DorraJaouad

**Comment by SystemKeeper** [comment]
Thought this was fixed by https://github.com/nextcloud/spreed/pull/10359. Leaving as a reference here.

**Comment by DorraJaouad** [comment]
It is related to the virtual scroller. As checked, it seems that `CONVERSATION_ITEM_SIZE` should be 69 or 70 instead of 68 to take into account the border's width. 
cc @ShGKme 

The [min-height](https://github.com/Akryum/vue-virtual-scroller/blob/0f2e36248421ad69f41c9a08b8dcf7839527b8c2/packages/vue-virtual-scroller/src/components/RecycleScroller.vue#L25) style for the wrapper is calculated based on the items' total size.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/10359 fixed left/right cut off 🙊

**Comment by ShGKme** [comment]
Fixing height with virtual scrolling could be tricky, we can just set `CONVERSATION_ITEM_SIZE=68px`, then it will act like margins are not collapsed, but visual margin between items will be 2 times large: `4px` instead of `2px` from `NcListItem`

**Comment by ShGKme** [comment]
Another alternative could be using `padding + border` instead of `outline`
