### ISSUE TITLE
Edit chat messages

### ISSUE THREAD

**Issue by gymnae** [nextcloud/spreed#10833]
I really don't think writing "begging" and marking a conversation as "too heated" regarding a much requested feature is a good way to communicate with your user base.

**Comment by nickvergessen** [comment]
Yeah and I think writing comments like "I want this too" instead of upvoting the ticket is not a good way to communicate with maintainers either. There are 62 comments on the ticket which means I received 63 notifications about this already, I receive more than 200 notifications in an average week.
We don't need more notifications about it.

We are aware that "everyone" has the feature. We are aware of the various usecases that exist for editing.
We are planning to look into it in the future, but as outlined it has coding tasks on all clients. Unless all clients understand the feature we can not release it.

**Comment by sunjam** [comment]
[You can allow emoji reactions on locked discussions](https://docs.github.com/en/discussions/managing-discussions-for-your-community/moderating-discussions).  Fwiw, allowing people to post unhelpful comments... might as well limit to emoji reactions.  :shrug:
