### ISSUE TITLE
Left sidebar handle misplaced on firefox

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#1098]
remaining task from #1092 

> ![bildschirmfoto von 2018-08-01 11-08-06](https://user-images.githubusercontent.com/213943/43512395-5312f3ba-957b-11e8-8bdd-9e40126722ca.png)

**Comment by nickvergessen** [comment]
Steps to reproduce:
1. Make the window small enough (< 1.000 pixels) so the sidebar is collapsed because you have a mobile device
2. Open the left sidebar

The fix would probably go into the css/styles.scss

**Comment by danxuliu** [comment]
This is fixed in Firefox >= 64.

In previous versions it seems that it could be fixed by overriding the [`position: fixed` set in the server for the navigation toggle](https://github.com/nextcloud/server/blob/b4e6bffe1d3baab95055b7bdfbcf6043a59b8d2b/core/css/mobile.scss#L61) with a static or relative position (although I have not tested it thoroughly yet, so I do not know if that could break other browsers/versions).

**Comment by nickvergessen** [comment]
If only FF <64 is broken and chrome and others work, thats good enough

**Comment by danxuliu** [comment]
Currently it is broken in Firefox < 64 and Internet Explorer 11, but works with Firefox >= 64, Chromium >= 62 and Edge >= 18 (I have not tested with Chromium < 62 nor Edge < 18, it may work too); I have not tested with Safari.

Setting the position to `absolute` makes it work too with Firefox < 64 and Internet Explorer 11; the other browsers are not affected by that change (I mean, they still work).

**Comment by nickvergessen** [comment]
That's good enough for me.
