### ISSUE TITLE
Group system messages, e.g. lots of people joining, or same person reconnecting

### ISSUE THREAD

**Issue by fancycode** [nextcloud/spreed#1148]
For larger / public meetings is doesn't make sense to have lots of "joined the call"/"left the call" system messages of (anonymous) users, so there should be a way to disable / hide them.

Opening here for further discussion on how the behaviour should be.

---

- [x] Frontend https://github.com/nextcloud/spreed/issues/9678
- [x] iOS https://github.com/nextcloud/talk-ios/issues/1265
- [ ] Android https://github.com/nextcloud/talk-android/issues/3073

**Comment by mario** [comment]
What about the ability to collapse them instead if you have more in a row?

**Comment by schiessle** [comment]
> What about the ability to collapse them instead if you have more in a row?

collapse them on a client level might make most sense because as mentioned here by @nickvergessen I agree that modifying messages in order to group them can be difficult once we have offline support.

**Comment by g-work** [comment]
Collapsing would be useful. But there should be one button to collapse all messages at once, because its quite annoying, that "normal" messages are difficult to find between all the system messages and it would be only little useful to collapse several groups of two, three system messages that are interrupted by normal messages.
I like the idea of some kind of log level which is decribed in #4297

**Comment by nickvergessen** [comment]
Current idea is to do some post-processing on the clients side:
* if there is a "rapid" (~5-10sec) left+join of the same user hide them and show a "X reconnected" instead
* if there are multiple joins/leaves from several people combine them to `A, B, C and X others joined the call` and `A, B, C and X others left the call`

**Comment by fabriziosalmi** [comment]
> For larger / public meetings is doesn't make sense to have lots of "joined the call"/"left the call" system messages of (anonymous) users, so there should be a way to disable / hide them.
> 
> Opening here for further discussion on how the behaviour should be.

To my opinion here we have 2 different problems which needs different solutions:

1. readability context
2. privacy context

**Readability context**
The best aggregation method will be used, the best UX will be achieved, in addition to that what about a totally different style for such kind of messages, bigger the content, smaller the feed update? I guess it can improve the overall chat room readabilty by far, especially on mobile devices. Maybe this will need less effort than the aggreation feature development :)
Of course the main goal is to improve content readability and there's not just 1 right way to achieve this mission.

**Privacy context**
As administrator I would like to selectively deny people to be informed about other's people activity, especially for public accessed chat rooms. This will decrease the whole attack surface, especially when Nextcloud servers are located in EU or any other privacy aware country.

**Comment by nimishavijay** [comment]
> if there is a "rapid" (~5-10sec) left+join of the same user hide them and show a "X reconnected" instead
> if there are multiple joins/leaves from several people combine them to A, B, C and X others joined the call and A, B, C and X others left the call

This sounds good! I would suggest that the time frame for this be increased to ~1 min. In many cases, a person leaves the call, refreshes the page and joins the call again, which I would consider as reconnecting. What do you think?

Ideas for UI and wording:

<img src="https://github.com/nextcloud/spreed/assets/52440189/3909a516-02d1-44b8-9573-10560cd03ea7" width=75% height=75%>

- [ ] The grouped message is shown, collapsed by default, with a toggle to expand and show the individual messages using the [unfold-more](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Aunfold_more%3A) MDI icon
- [ ] Clicking on the expand button shows the individual system messages along with the timestamp (not pictured in the screenshot) as it is shown right now
- [ ] In the expanded state, the toggle icon is [unfold-less](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Aunfold_less%3A)
- [ ] Single messages: `A joined the call`
- [ ] two messages: `A and B joined the call`
- [ ] three messages: `A, B and C joined the call`
- [ ] more than three messages: `A, B and 2 others joined the call`
- [ ] leaves and joins within 1 min: `A reconnected`
- [ ] added to conversation: `A added B, C and 2 others to the conversation`
- [ ] promoted to moderator: `A promoted B, C and 2 others to moderator`
- [ ] nice-to-have: group together anonymous user messages as `5 guests joined the call`, instead of `Guest, Guest and 3 others joined the call`

What do you think? :) cc @nextcloud/designers for any more feedback :)

**Comment by marcoambrosini** [comment]
Very nice improvement, the only thing I think we could improve is the button. It doesn't look like a button and I think we could find a better icons to represent the action. How about regular chevron icons?

**Comment by nimishavijay** [comment]
> Very nice improvement, the only thing I think we could improve is the button. It doesn't look like a button and I think we could find a better icons to represent the action. How about regular chevron icons?

That was actually v1 of this! :) We noticed that the "scroll to bottom" has the same icon, and it could cause confusion (esp in small screens where they might be right next to each other or overlapping)

**Comment by nickvergessen** [comment]
Closing as MVP parts are done for the upcoming release
