### ISSUE TITLE
Are email usernames supported?

### ISSUE THREAD

**Issue by jandechent** [nextcloud/spreed#11834]
I did set up "everything" using https://github.com/sunweaver/nextcloud-high-performance-backend-setup
From the start I configured two nextcloud servers

1. Everything works with my private nextcloud. STUN, TURN and TURNS,  HPB
2. With the other nextcloud server it does not work. Chat messages are super delayed, no video calling possible. This is at a different hoster. When putting in the settings for STUN, TURN and TURNS,  HPB in the nextcloud, we do see green check marks.

Question
`nextcloud-spreed-signaling-server[550]: hub.go:757: Register user jenna@gmx.net@nextcloud-backend-1`
Do you support "@" as usernames from the nextcloud? 

Could this trigger other errors like
`nextcloud-spreed-signaling-server[550]: backend_client.go:204: Throttled OCS response {"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}} from https://secretserver.de/ocs/v2.php/apps/spreed/api/v3/signaling/backend
`
which is often followed by 
`nextcloud-spreed-signaling-server[550]: client.go:302: Error reading from 19.143.78.28: read tcp 127.0.0.1:8080->127.0.0.1:46620: use of closed network connection`
 There is no extra app running for brute force limiting.

**Comment by nickvergessen** [comment]
429 means you got brute force protected
We have quite some people with email addresses joining calls on our server so that should work in general.

Can you confirm the remote address your high-performance backend (nextcloud-spreed-signaling-server) is using to access the nextcloud is correct and not a (reverse) proxy IP address?
If it is really the local IP of the HPB, feel free to reset the bruteforce attempts for it (and make sure you have the correct secret configured)
If you are really sure you can also exclude it from bruteforce to avoid issues in the future: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html#excluding-ip-addresses-from-brute-force-protection

**Comment by jandechent** [comment]
Embarrassing, indeed it was the brute force protection. I think, when copy and pasting the secret, I copied "too much", so the secret was wrong, but only once :/
