### ISSUE TITLE
Removing a team/group from the conversation throws actor out of it, if actor is a member of them

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#11875]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Be a member/owner of a team/group
2. Be a moderator/owner of a conversation
3. Invite team/group to a conversation
4. Remove team/group from a conversation

### Expected behaviour
Every member except the actor should be removed from the list (and leave conversation)

### Actual behaviour
Every member including the actor left conversation, although actor stays as a last moderator (also both last moderators will stay)

**Comment by nickvergessen** [comment]
I can not reproduce and actually all non-users are always skipped:
https://github.com/nextcloud/spreed/blob/2ee2183331b0207b3989087494e5857d97dbd90d/lib/Service/ParticipantService.php#L919-L922

And since only moderators and owners can remove groups the actor is that and not a user and so they should be skipped properly.

**Comment by Antreesy** [comment]
Ok, also can't reproduce anymore =/
