### ISSUE TITLE
🧭 Calls in Safari

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12455]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Unclear
2.
3.

### Expected behaviour
Calls work properly

### Actual behaviour
Some people report that calls are not working

## Talk app

**Talk app version:** Latest 19

**Custom Signaling server configured:** yes 1.2.4-1~ubuntu20.04 

**Custom TURN server configured:** yes

**Custom STUN server configured:** no

## Browser

**Microphone available:** yes/no

**Camera available:** yes/no

**Operating system:** Mac

**Browser name:** Safari

**Browser version:** 124/125/...

**Comment by nickvergessen** [comment]
### Steps

1. You join the call with Safari
2. You switch to something else
3. Someone unmutes and starts speaking

### Problem

You can not hear the user from Step 3?

**Comment by nickvergessen** [comment]
> Either step is unclear, or it's not always reproducible. (hide window, switch tab, make window inactive - what exactly?)

Yeah it's unclear/wage at the moment. Might require a certain amount of inactivity, maybe also a certain number of already active audio streams, so it's preventing the tab to abuse resources at some point, etc.

**Comment by SystemKeeper** [comment]
Yea, haven't seen this. Safari also has an option to enable WebRTC debug output, which might be helpful if it's WebRTC related.

**Comment by danxuliu** [comment]
In order to play audio [you need to interact with the page first](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) (for example, by clicking on the `Join call` button). The problem could be that Safari, if a window is inactive for some time, resets the autoplay permission until the user interacted again with the page.

It looks like a bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=262952

There is another bug that could be related as well (apparently involving transceivers made inactive, which we do when blocking remote video), although the other one seems more promising: https://bugs.webkit.org/show_bug.cgi?id=211181
