### ISSUE TITLE
Talk App Freezes After Starting A Call In Safari

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/spreed#12579]
## Steps to reproduce
1. Start video conference with using Safari browser
2. Web app freezing. After 10 - 15 seconds, it will become a normal.

### Expected behaviour
Web app shouldn't freeze

### Actual behaviour
Web app freezing after start video conference 

## Browser

**Microphone available:** Yes

**Camera available:** Yes

**Operating system:** Mac OS Sonoma 14.5

**Browser name:** Safari

**Browser version:** 17.5

**Comment by SystemKeeper** [comment]
Saw the same now a few times, UI just freezes. I was unable to figure out what the root cause it.
All cases mentioned here only happen *sometimes*

* While one participant is in the call
  * Join without camera and microphone -> UI Freezes
  * Leave the call -> UI Freezes

* While noone is in the call
  * Try to start a call, with no camera and no mic selected -> UI Freezes
  * Leave the call -> UI Freezes

So it seems not webrtc related at least 🤷

**Comment by SystemKeeper** [comment]
Hm, couldn't reproduce it anymore. There must be something specific happening that triggers this kind of behavior...

**Comment by nickvergessen** [comment]
Talk was updated Thursday night. Maybe a change in the vue library update fixed something?

**Comment by SystemKeeper** [comment]
@alperozturk96 is it still reproducible for you?

**Comment by alperozturk96** [comment]
Same

**Comment by SystemKeeper** [comment]
Would you be able to test the following please?
* Open the developer tools
* On the `body` element you should find a variable called `--animation-quick`
* Change the value to 0
* Try to reproduce the issue again

**Comment by alperozturk96** [comment]
Seems like it's working now. I tried the bunch of calls back to back, no issue at all.
