### ISSUE TITLE
Mic icon is not toggled when being muted by a moderator in a federated call

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12797]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. UserA on ServerA creates a conversation and invites UserB on ServerB
2. UserA starts a call
3. UserB joins the call
4. UserA presses the "mute icon" for UserB

### Expected behaviour
UserB should see that they are muted

### Actual behaviour
![grafik](https://github.com/user-attachments/assets/61a1381c-d352-4940-a002-347f3e266a13)

Also every now and then UserB got unmuted for me when toggling the camera as UserB or other things

**Comment by danxuliu** [comment]
To force mute another participant [a control message is sent to every participant in the call](https://github.com/nextcloud/spreed/blob/1f2ba38538949ff5ada402ecc3cd106b525028a6/src/utils/webrtc/models/CallParticipantModel.js#L168-L171); the client of the target participant [should mute itself when the message is received](https://github.com/nextcloud/spreed/blob/bebc2f9cddd398f3b989d3a3bd2760eb313c95fe/src/utils/webrtc/simplewebrtc/simplewebrtc.js#L111-L115), but the clients of other participants will also [locally mute the target participant](https://github.com/nextcloud/spreed/blob/bebc2f9cddd398f3b989d3a3bd2760eb313c95fe/src/utils/webrtc/simplewebrtc/simplewebrtc.js#L117). This ensures that even if the client of the target participant does not mute itself for some reason in practice it will be muted for the rest of participants (or, at least, for those currently in the call).

Due to all that the `forceMute` control message includes the session ID of the target participant in its payload:
```
{
    type: 'control',
    control: {
        sender: ...,
        receiver: ...,
        data: {
            action: 'forceMute',
            peerId: SIGNALING-SESSION-ID-OF-THE-TARGET-PARTICIPANT,
        }
    }
}
```

For a federated user, its own signaling session ID and the ID seen by other participants is different, so the `peerId` needs to be converted. The signaling server takes care of that in other cases, but [for `control` messages currently only the `receiver` and `sender` fields are converted](https://github.com/strukturag/nextcloud-spreed-signaling/blob/451ad5c26e17a1f1318fb631fd7a8666b8f155cc/federation.go#L611-L613).

@fancycode Could `control->data->peerId` be converted as well? :-) Thanks!

**Comment by fancycode** [comment]
Implemented in https://github.com/strukturag/nextcloud-spreed-signaling/pull/776/commits/0fc9487cc7bc99add963c998f3fd9a09bd2c9701

**Comment by fancycode** [comment]
Btw, it should be possible to send a single message to the `room` recipient and let the signaling server handle distribution to all participants internally.

See https://github.com/strukturag/nextcloud-spreed-signaling/blob/4bb9e614f4d22c7177526d5523130533ec9cd32a/docs/standalone-signaling-api-v1.md?plain=1#L762-L775

**Comment by danxuliu** [comment]
> Implemented in [strukturag/nextcloud-spreed-signaling@0fc9487](https://github.com/strukturag/nextcloud-spreed-signaling/commit/0fc9487cc7bc99add963c998f3fd9a09bd2c9701)

Tested and works :+1: Thanks!

> Btw, it should be possible to send a single message to the `room` recipient and let the signaling server handle distribution to all participants internally.
> 
> See https://github.com/strukturag/nextcloud-spreed-signaling/blob/4bb9e614f4d22c7177526d5523130533ec9cd32a/docs/standalone-signaling-api-v1.md?plain=1#L762-L775

Opened an issue for that in https://github.com/nextcloud/spreed/issues/12881
