### ISSUE TITLE
Frontend for "Recognize email guests"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13606]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

- Follow up to #6098 

---

## 🖌 Frontend

- [ ] We don't want to distinguish between guests and email-guests anymore in the UI 
  - [x] Show account icon for both moderators and users (👤, no questionmark anymore, should be the same as for former-one-to-one)
  - [x] Show first letter when a custom name is set
  - [x] Only show email icon for moderators when searching / adding a new participant (invite e-mail)
  - [x] Show always (guest) badge
  - [x] Show always on grey background
  - [x] Show the invited email address to moderators in the participants list
  - [ ] Check "Guest (Guest)" intermediate name ? (Web - do not pass default "Guest" or "Deleted user" to AvatarWrapper)
- [x] Resending the invite shows the ID instead of the name
- [ ] Guest name dialog
  - [ ] Show the invited email address on the "Guest name screen"
  - [ ] Should we hide the "have an account, login here?" message from that screen?
- [ ] Other places:
  - [x] Check mentions (note their guest ID is longer than the old guests actor id and therefore potentially the regex needs adjusting)
  - [x] Mail address should be shown in auto-complete, but not in mention-chips
  - [x] Check autocomplete
  - [ ] Check call view
  - [ ] The mail address is shown for moderators in the callview and message sender (like it's done for federated users)
  - [ ] Mention and sender is missing from API -> Needs to be clarifies by Joas if it's possible

---

- [x] https://github.com/nextcloud/talk-android/issues/4363
- [x] https://github.com/nextcloud/talk-ios/issues/1847

**Comment by SystemKeeper** [comment]
1. Currently for an email invite it shows "Guest (Guest)" in the participant list:
   <img src=https://github.com/user-attachments/assets/73303da9-c88b-4fc4-a021-76ec604c5a58 width=250 />

   Should the email be shown there? Only for moderators? (Property `invitedActorId`).

2. Show ? when "default Guest" name is used (?)
   Since we enforce a guest name nowadays, this will never be the case?

**Comment by nickvergessen** [comment]
That's exactly what the ticket is about 😅

**Comment by SystemKeeper** [comment]
> That's exactly what the ticket is about 😅

I don't see any of my questions addressed in this initial post 😅

**Comment by SystemKeeper** [comment]
Resending the invite shows the ID instead of the name:

![Image](https://github.com/user-attachments/assets/562ebf1f-58df-4c44-9e21-2e92bff11717)


There seems to be a race condition somewhere in the frontend, when trying to resend the invitation in the wrong moment, it's send to another participant (might be a general problem with the menu we had in the past?)

![Image](https://github.com/user-attachments/assets/a82059dc-d2d1-4570-ae0f-9740d9a6f9df)

**Comment by nickvergessen** [comment]
> I don't see any of my questions addressed in this initial post 😅

Right, I had only talked about those with Ivan and Maksim at the office. Anyway, edited the first post.

**Comment by Antreesy** [comment]
Noticed while testing
<img width="223" alt="image" src="https://github.com/user-attachments/assets/c25ee0c7-3af6-4693-9b5a-30109f2d2ad2">

**Comment by nickvergessen** [comment]
@Antreesy All done by now, so we can close?
