### ISSUE TITLE
Federated calls when instances use the same signaling server

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#13671]
Hello, is the scenario in which the federated calls are on two instances that are defined on the same signaling server supported?

I'm doing some tests with:
- Nextcloud server v30.0.1
- nextcloud-spreed-signaling: 2.0.0

With the same two instances, calls work if I define them on different signaling servers and calls don't work if I define them on the same signaling server.

"Don't work" here means that the participants don't see each other in the call even if event messages suggest so.

I can provide more details (logs.. etc) but first wanted to check if there is already some root cause known.

**Comment by nickvergessen** [comment]
What was the state @fancycode

**Comment by fancycode** [comment]
@nickvergessen You had a similar problem with two instances using the same signaling server during development. However this was fixed with https://github.com/strukturag/nextcloud-spreed-signaling/pull/808/commits/b233651db0464ea383f6b1f4330fc34d1e54c0b4 which is part of 2.0.0.

So from my point of view this *should work* although I haven't tested this in a while.

**Comment by SystemKeeper** [comment]
This is basically my development setup and works fine for me

**Comment by pmarini-nc** [comment]
For me it doesn't work and I'm using nextcloud-spreed-signaling 2.0.0. @fancycode, any pointer on which error I should look at in the logs?

**Comment by pmarini-nc** [comment]
The behaviour in my setup in a screen recording
[vokoscreenNG-2024-10-30_21-41-42.zip](https://github.com/user-attachments/files/17578895/vokoscreenNG-2024-10-30_21-41-42.zip)

**Comment by fancycode** [comment]
> @fancycode, any pointer on which error I should look at in the logs?

The problem @nickvergessen had in the past was that users got randomly disconnected while in a federated call. This was due to pings from the signaling server to Nextcloud were missing in some cases. However this was fixed with the above commit.

Your problem looks different, so looking at the logs as @SystemKeeper suggested would also be my first guess. In addition, please check your Nextcloud log for any errors.

**Comment by pmarini-nc** [comment]
My bad, it was a network configuration issue. The signaling server was not able to connect to itself:

`Error creating federation client to https://my.signaling.name/ for 8yYnBLI7ZN[..] to join room 92jc9nn2: dial tcp XXX.XXX.XXX.XXX:443: i/o timeout`

Sorry for the noise and thanks all for the support!
