### ISSUE TITLE
Via link conversation is not persistent

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#1377]
## Steps to reproduce
1. create a public room on localhost/nc
2. open it on android (due to the internal dns the link is http://10.0.2.2/nc/…
3. have conversation
4. go back 
5. see conversation list, but not joined public room from 2.

### Expected behaviour
Still be able to join rgoom

### Actual behaviour
No room visible

Everything on latest master.
Android on branch: contacts-new-conversation-rework○

**Comment by nickvergessen** [comment]
Yes, public link conversations are automaically left after leaving so the potential password has been reentered everytime. This is currently the desired behaviour

**Comment by Ivansss** [comment]
Hi Tobias :)
Just to be clear, let me know which case is your case:

Case 1:
User A from instance A creates a public room
User B from instance B follow that link using the Android app

Case 2:
User A from instance A creates a public room
User B from instance A follow that link using the Android app

If it is the first case, then you should open an issue in the Android repo.
Since the client needs to remember that link and present it as a room in the room list.

**Comment by mario** [comment]
Will follow-up here after I've discussed this via IRC on our #android-talk channel. This sounds strange to me that the client should remember the links the user joined. If we want this, then it has to go into all clients (including web).

**Comment by tobiasKaminsky** [comment]
@Ivansss Case2, both are on the same server (localhost).
But as mentioned in first post, I have to use 10.0.2.2 as localhost on android is directing to its device.

**Comment by tobiasKaminsky** [comment]
> Yes, public link conversations are automaically left after leaving so the potential password has been reentered everytime. This is currently the desired behaviour

I would have expected that at least the room is remembered in list. If it is password protected, then the clients can ask again for the password.
