### ISSUE TITLE
No return of the profile picture

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/spreed#1528]
### **Steps to reproduce**
1. Creating a connection.
2. Adding a user to the conversation.
3. Share the link with the guest.
4. Remove the guest from the conversation.

### **Expected behaviour**
Returns the profile picture after all guests have been removed from the conversation.

### **Actual behaviour**
After disabling access to guests in the connection, the profile picture of the previous user does not return.

![obraz](https://user-images.githubusercontent.com/47037905/52521287-267c8000-2c75-11e9-8b79-07e63437cbaa.png)

![obraz](https://user-images.githubusercontent.com/47037905/52521305-807d4580-2c75-11e9-98d0-e441135cf9de.png)

After removing the conversation and after reconnecting, the profile picture appears correctly.

### **App**
Nextcloud v15.0.4
Spreed v5.0.2

**Comment by nickvergessen** [comment]
Works fine for me with the steps you listed.

Maybe you can extend the steps and point out where exactly you clicked?

**Comment by Valdnet** [comment]
### Steps to reproduce:
1. Create a new connection with the registered user.
2. Create a new connection with a registered user who has their profile picture.
![obraz](https://user-images.githubusercontent.com/47037905/52581439-08f11700-2e2b-11e9-8d30-1a78b20c652a.png)
3. Select the `Share link`:
![obraz](https://user-images.githubusercontent.com/47037905/52581600-6e450800-2e2b-11e9-9a5b-e7c088dec820.png)
 - the profile picture will change to: 
![obraz](https://user-images.githubusercontent.com/47037905/52581020-e9a5ba00-2e29-11e9-8677-f2a5480fd7de.png)
4. Uncheck the `Share link`:
![obraz](https://user-images.githubusercontent.com/47037905/52581129-3c7f7180-2e2a-11e9-8959-27a48f76116d.png)
5. No return to the registered user's profile picture:
![obraz](https://user-images.githubusercontent.com/47037905/52581711-b532fd80-2e2b-11e9-880a-136b72826900.png)

**Comment by Ivansss** [comment]
Hi @Valdnet,

This is the "expected behavior".

User A has a private conversation with User B.
It's only possible to have just one private conversation between 2 users at the same time.

Once user A or B selects "Share link",that private conversation becomes a public group conversation.

During this time, user A or B can create a new private conversation between them.

In order to avoid conflicts (2 private conversation between A and B at the same time), when user A or B unchecks "Share link" in the first conversation, this conversation becomes a private group conversation.

**Comment by Valdnet** [comment]
> During this time, user A or B can create a new private conversation between them.
I have not thought about this possibility.

@Ivansss Thanks for such a comprehensive answer.
