### ISSUE TITLE
Allow chooseable own video position

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/spreed#155]
At least on mobile phone where the distance between display and face is not that far it would be good to have a chooseable position of the own video. Otherwise the other user thinks that the user is looking down/at the bottom most of the time. 
Ideally the own video should be in the near of the selfie video cam.

**Comment by jancborchardt** [comment]
An issue here is the layout. Since we need to scale to group calls, we opted for a row of videos on the bottom, of which the speaking one is promoted to full view and your own video is always in the bottom right.

We could potentially move the row to the top on mobile. But checking other solutions like Skype, Facetime, Hangouts, and Whatsapp the default is to have the own picture on the bottom right. So it doesn’t seem to be that big of a complaint and changing that to be on top by default would be strange.

**Comment by nickvergessen** [comment]
Closing as per above
