### ISSUE TITLE
Recent chat history missing after switching conversations

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#1797]
## Steps to reproduce
1. Have group conversation A
2. Switch to 1:1 conversation B
3. Get mobile notifications for A
4. Switch back to A (all via web)

### Expected behaviour
See most recent messages from A.

### Actual behaviour
Miss A history, but not only the new, unseen messages but also ones from the last few hours.

## Browser

FF

**Comment by wiswedel** [comment]
iOS client 6.1.0 is working well by the way. Whole chat is displayed.

**Comment by ChristophWurst** [comment]
Yep, Android is also fine. It's just happening on the web client.

**Comment by nickvergessen** [comment]
Can not reproduce locally, so this seems to be an issue with the external signaling

**Comment by MorrisJobke** [comment]
> Can not reproduce locally, so this seems to be an issue with the external signaling

Could it be related to very long chat history? Because I only see it in the bigger channels.

**Comment by wiswedel** [comment]
A look into the browser's debugging console reveals the following request URL:

https://cloud.nextcloud.com/ocs/v2.php/apps/spreed/api/v1/chat/ngpbtmn7?lastKnownMessageId=18584&limit=100&lookIntoFuture=1&timeout=0

If you curl that with **limit=-1** instead of limit=100, it shows everything. Otherwise curl gives the same output as we see in the web UI now.
