### ISSUE TITLE
Show nice empty content warning if HTTP is used

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/spreed#18]
Some browsers enforce HTTPS for WebRTC.

https://quickblox.com/blog/no-more-http-for-webrtc-on-chrome-only-https/

**Comment by jaller94** [comment]
Please clarify the expected behaviour, for example:
1. Test if `getUserMedia` is supported (has to be done anyway)
2. Warn about using HTTP first but offer a button to connect anyway
3. Block all browsers when connecting via HTTP

Does it come with any risks for connected partners? Is it worth warning them about an insecure partner?

**Comment by fancycode** [comment]
I think this can be closed with the changes from #41. Users connecting through HTTP see the reason why they can't use their local media.

Feel free to reopen if you want anything else done here.
