### ISSUE TITLE
Mobile View: should open the chat list first

### ISSUE THREAD

**Issue by szaimen** [nextcloud/spreed#1937]
**Is your feature request related to a problem? Please describe.**
The default side when opening the chat app on mobile isn't very compelling: I'm not seeing the chats.

**Describe the solution you'd like**
I think on mobile view when I open the talk app it should open the chat list first.

**Additional context**

1. The default view when opening the chat app:
![20190702_014048](https://user-images.githubusercontent.com/42591237/60472886-01f86300-9c6b-11e9-8273-0450dc9d12c4.png)

2. Probably a better default site:
![20190702_014637](https://user-images.githubusercontent.com/42591237/60473017-94006b80-9c6b-11e9-9eab-e309ece7ef5e.png)

**Comment by danxuliu** [comment]
@nextcloud/designers You can test this feature by adding
```
})(OC, OCA, Marionette, Backbone, _, $);

$(document).ready(function () {
	if ($(window).width() <= 600) {
		$('#app-navigation-toggle').click();
	}
});
```
at [the bottom of _app.js_](https://github.com/nextcloud/spreed/blob/f374cf37592a57d0ccce55ea75e4330c7293c17d/js/app.js#L926).

It is a bit hacky, but it is necessary to wait until [the snapper is initialized by Nextcloud server](https://github.com/nextcloud/server/blob/master/core/src/init.js#L303-L304) (which is done in a [jQuery `ready` handler](https://github.com/nextcloud/server/blob/51d49c3134c9acf7e2daba5bcc8c87e14a7548f1/core/src/main.js#L34-L35)), and I am not aware of any events that could be listened to for that.

If this behaviour should be added to Talk, which window width should trigger it? Note that when the navigation bar is opened it moves the app contents of Talk to the right, so the _Join a conversation or start a new one_ message is cut with some width sizes which, in my opinion, does not look good for the starting page (that is why I used 600px in that example code instead of the standard 1024px of the mobile breakpoint; at 600px the message is cut too, but most of it is hidden anyway which in my opinion looks better than just cutting the final letters ;-) ).

**Comment by jancborchardt** [comment]
@danxuliu good one! I’d say let’s always make sure the sidebar shows on views where it wouldn’t be, so 1024. We can always enhance the emptycontent view.

**Comment by rubo77** [comment]
This is totally unusable on my screen on Firefox, Android 10 Samsung a6 NC19.0.1

![Screenshot_20200722-005147_Firefox](https://user-images.githubusercontent.com/1591563/88115391-4d531b80-cbb6-11ea-985b-63ec5e7e5639.jpg)

**Comment by szaimen** [comment]
@rubo77 I think this is doesn't have anything to do with this issue. 
Could you please open another issue with that?

**Comment by jancborchardt** [comment]
@ma12-co something for you :)

**Comment by ma12-co** [comment]
@szaimen  that's related because that's what you actually see on first load since the rewrite to vue.
Ok, so as discussed, the sidebars behavior on mobile should be:

- On first load, the conversations list is displayed;
- A click on a conversation routes to it and automatically closes the left sidebar;
- The right sidebar is never shown unless toggled;

**Comment by nickvergessen** [comment]
Just a little comment, when you directly load into a conversation it should also hide the left sidebar

**Comment by szaimen** [comment]
In order to fix the messy layout for mobile when joining a chat we may need to change this function https://github.com/nextcloud/spreed/blob/9a00b48798ae3d5f38e2070166954edcee09de99/src/App.vue#L442

**Comment by szaimen** [comment]
Regarding this feature: we may be able to open the sidebar automatically using https://github.com/nextcloud/nextcloud-vue/blob/cd98e1dedd3f265ab6555041f198f59a470b5b27/src/components/AppNavigation/AppNavigation.vue#L38-L42 if the viewport ismobile is true and of course only if on the start page

See also https://github.com/nextcloud/nextcloud-vue/blob/cd98e1dedd3f265ab6555041f198f59a470b5b27/src/components/AppNavigation/AppNavigation.vue#L87

**Comment by PVince81** [comment]
I was about to report the sidebar not closing automatically, it's also an issue on narrow screens, not only mobile. For example on the company instance if you narrow the screen horizontally, it switches to "hamburger menu" mode and it's very annoying that when I switch conversations I need to manually close it (and I switch often).

should "mobile view automatically open sidebar" and "close it when selecting an entry or clicking inside the conversation" be separate tasks/topics ?

is old Snapper from server an issue ? I remember that there were ideas/plans to get rid of it / replace it
