### ISSUE TITLE
doesn't work, no connection? 

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/spreed#200]
Hi, two users in nextcloud can't connect. 
Going to the calls app, choosing the other user, everyone sees his own video in the bottom right corner and the avatar of the other in the middle.
Message is: waiting for the other user to join the room. But how? There is no button etc.???
What about a documentation?

**Comment by jancborchardt** [comment]
Hey @axel-rank, do you have any errors in the browser console? (When you right-click and inspect the page.)

And which browsers do you use?
Also does it work when one of the people refresh? Or both?

**Comment by sushidave** [comment]
@axel-rank And are they users on the same Nextcloud? I'm asking because the federated calls feature (between different Nextcloud instances) is in the planning, see #21.

**Comment by axel-rank** [comment]
@sushidave 
Yes, they are users on the same nextcloud.
@jancborchardt 
We use latest Firefox.
Browser Console:
![spreed](https://cloud.githubusercontent.com/assets/12480617/21954348/65167698-da4e-11e6-8730-5fad78c56891.png)

**Comment by jancborchardt** [comment]
Any idea @Ivansss?

**Comment by axel-rank** [comment]
To be precise: 
The test reported in my last post was without a Webcam on a local network. So related to issue #160 this couldn't work at all?
I will try again next week on a live session with cam again.

**Comment by nickvergessen** [comment]
Firefox does not work without a webcam atm. We are working on that in #179

**Comment by STonEDSTonE** [comment]
I tried to test a bit since i had a similar problem.
I opened Chrome and followed a public link with Chrome as guest, it worked.
I aditionally opened Firefox and followed the public link with Firefox as normal User, it worksed.
I logged out of the normal user and followed the public link with Firefox as guest, it didn't work, regardless of Webcam used or not (see attatched Screenshot).
I close Firefox and follow the public link with Firefox as guest again, it now works.
So sometimes a Browser restart works wonders :)
