### ISSUE TITLE
Missing Add participant... form in conversation

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [nextcloud/spreed#2140]
## Steps to reproduce
1. Open Talk page
2. Create new conversation
3. Try in right sidebar add participant...

### Expected behaviour
I can't see form with Add participant - it's missing. But I can found in developer tools - with css style display: none  

Any browser. Nextcloud 16.0.4 (clean installation); Talk 6.0.4

When I delete css style with display:none - form showing. But when I choose somebody in them I get error in developer tools console tab:

https://nextcloud.vz/ocs/v2.php/apps/spreed/api/v1/room/qyg3mru6/participants 400 (Bad request)

**Comment by nickvergessen** [comment]
Are you a moderator of the room?

**Comment by strelkovandreyvalerievich** [comment]
Yes, both user moderator
Right now I start new demo https://try.nextcloud.com/chaj7iew
And there is exactly the same behavior

**Comment by Ivansss** [comment]
Since [Talk 6.0](https://github.com/nextcloud/spreed/releases/tag/v6.0.0) one-to-one conversations can not be turned into group conversations.

You can create group conversations (private or public) directly from the top-left dropdown menu.
<img width="297" alt="Screenshot 2019-08-30 at 15 27 51" src="https://user-images.githubusercontent.com/4638605/64024718-5325b580-cb3b-11e9-85ca-5f32485155c2.png">

Start typing the name of the conversation you want to create, and then select one of the 2 options (private or public)
<img width="307" alt="Screenshot 2019-08-30 at 15 28 06" src="https://user-images.githubusercontent.com/4638605/64024812-8a946200-cb3b-11e9-8d0d-85126c76b6a5.png">

**Comment by nickvergessen** [comment]
In Talk6 we changed how one-to-one conversations work and you can not add users to those. You have to create an empty conversation or a group conversation by starting to type the name of the conversation or group

**Comment by strelkovandreyvalerievich** [comment]
That's it! I'm confused, I'm sorry, I understand now. Question can be close =)
