### ISSUE TITLE
Add permissions to groups to create new discussions

### ISSUE THREAD

**Issue by vincowl** [nextcloud/spreed#2285]
It would be great to be able to define which groups can create new discussions (by default to everyone). This would allow an admin group to create a set of chatrooms and share them among groups. Users in groups would see their allowed rooms, talk inside these but would not be able to create new ones. This would help fighting against unwanted discussions.

**Comment by nickvergessen** [comment]
I'm not sure if we want to and should do this. But I will leave it open for now

**Comment by tobiasKaminsky** [comment]
Any other chat system I am aware of (not that many though) do not have such.
In NC cases, I could imagine that a restriction whom to invite based on groups might make sense.

In opposite of the above idea, it would then be that an user can only create conversations with its group (and therefore only add users from this group).

Image you have a school, with many classes (= groups) and each class can have as many conversations as they like within their group.

**Comment by nickvergessen** [comment]
That can already be achieved because the relative share setting is respected.

**Comment by alexanderdd** [comment]
> That can already be achieved because the relative share setting is respected.
@nickvergessen can you please explain how this works or point me to documentation?

We have a need for this (education institution). Currently, every student can create a new room, invite all teachers (via teachers group) and start chatting. We would like to set a permission for users in the "students" group that they can not create group chats (because group chats are created by admin), only individual chats.
