### ISSUE TITLE
Ability to start call with camera & mic on

### ISSUE THREAD

**Issue by wouterVE** [nextcloud/spreed#2485]
**Is your feature request related to a problem? Please describe.**
When you start a call - the camera & microphone is always muted. The user has to switch it on manually every time using the appropriate buttons on the bottom of the screen.
This works confusing for some users as they think the call is not working. 

**Describe the solution you'd like**
An ability (e.g. in the admin settings page) to set a default behaviour when starting a call.
For instance: a checkbox for the following options

- Start microphone muted
- Start webcam muted

Probably, this option can be split up between 'normal' calls and 'lobby' calls (i.e. webinars) as in the latter case, it can be preferred to start muted until the webinar actually starts.

**Additional context**
Until NC15, Talk started the camera + mic automatically. With this option, administrators can choose themselves if it is important for calls to start muted or not.

**Comment by nickvergessen** [comment]
Starting with audio and video disabled is a "save is better then sorry" decision in general. I guess it would help to make it more obvious how/where to enable your audio/video.

As for video there is one more thing to consider:
Starting with video of is also a performance decision. When you turn it off after it was enabled, you upload and the other persons download, a black video stream in the same resolution and quality and FPS as your video before. Since it is fully one color only, it's not as bad as a video, but it is a noticable performance impact on your users.

**Comment by ma12-co** [comment]
I agree with the need of dealing with this because the average user definitely encounters a barrier there IMO. 
I also think it's safe to assume that when someone clicks 'join call', he/she is aware that his/her mic is going to start to listen :p
 
So I would propose that we default with mic and camera on and @nickvergessen, to address the 'safe is better than sorry' concern we can try to be more explicit about the fact that you're joining the call :)

We could do it in the new TopBar component, right below the header in the main content. Just did a quick mock up of how it could look: 

![Screenshot_20191126_163355](https://user-images.githubusercontent.com/26852655/69647882-91fbd680-106a-11ea-8f02-5f84867ec292.png)

![Screenshot_20191126_163556](https://user-images.githubusercontent.com/26852655/69648039-d6877200-106a-11ea-8442-c6a4a954b590.png)

What do you think @nickvergessen @nextcloud/designers?

**Comment by jancborchardt** [comment]
@ma12-co that’s a bit of a busy bar with lots of unlabeled icons. :\ And we talked before that we shouldn’t have a permanent bar there?

A simple first step enhancement to the current state:
- We now clearly separate group calls and 1on1 calls
- For 1on1 calls, you know exactly who is going to hear you, which is 1 person
- → We could start 1on1 calls with mic on, as opposed to group calls.

**Comment by ma12-co** [comment]
@jancborchardt, the only new unlabeled icon is the search, the others are already there in the current app, they are more or less in the same spot.
The searchbox  could be permanent or toggle-able I guess, depending on the width available maybe? 

>And we talked before that we shouldn’t have a permanent bar there?

We did, but we were only taking into account the 2 sidebar toggles and the call button. We weren't considering the fullscreen button and the search feature. So all these things are getting a bit out of control imo, and I feel like we could give it some harmony by grouping them as nice as we can in the topbar, that's why I brought back the idea. btw, my mock-up is not meant to look nice, but rather just to showcase this idea.

Plus, this is a screenshot of the current situation, effectively we have 2 vertical bars on the sides of the chat. So we'd still be cutting on used space.

![Screenshot from 2019-12-01 17-23-30](https://user-images.githubusercontent.com/26852655/69916803-b3403680-145f-11ea-9114-29fe1784d4bd.png)

**Comment by jancborchardt** [comment]
@ma12-co let’s keep this issue focused on what it is about though. :) Top bar stuff should be in a separate issue, or ideally we should have a call about it?

**Comment by ma12-co** [comment]
You're right @jancborchardt , let's discuss all this tomorrow then!

> → We could start 1on1 calls with mic on, as opposed to group calls.

About this, I can't really tell whether that's going to be intuitive or confusing. Since we have to do the call flow and view from scratch, maybe we discuss it all in the call tomorrow as well?

**Comment by wouterVE** [comment]
@ma12-co ,
Hello,
has there something been decided regarding the call flow (ie mic/video auto on or not)?
kr
wouter

**Comment by nickvergessen** [comment]
Not yet

**Comment by apiraino** [comment]
@nickvergessen I understand and share the privacy concerns of the team, just let me add my humble feedback to this issue. 

Disabling the mic+cam by default **after the browser asks the user for this very permission** and **the user willingly grants the permission** is an additional friction point that does not bring value.

I second the proposal to let the user decide which features to join the call (audio only or audio+video). whereby.con (a.k..a. appear.in) uses this and I don't find the UX clumsy. 

Still, I love NC Talk and I see a lot of potential :+1:

**Comment by Refhi** [comment]
Making consultations over video during the outbreak Nextcloud Talk proved too hard for most patients.
I went to Jitsi meet and really enjoyed the instant-visio experience, very user-friendly

I'd love to just send a link to my patient, they clic and see me instantly

**Comment by wouterVE** [comment]
My further thoughts: for IT-minded people like us  it's  obvious that you have to press the mic & cam to enable it but for the average user it isn't. First reaction of them: it doesn't work let's call IT for assistance. 

It think it would be a good addition to make it clear to the user whether to join the call with audio or audio+video.  
Would be easier to understand for for the average user and less support calls us admins :-)

Thanks for this awesome software!

**Comment by Refhi** [comment]
Many apologies if my previous comment was misplaced (I just noticed it was marked as Spam)

As a doctor I was just trying to emphasis my eagerness to see a one-clic link to video conversation within Nextcloud Talk with sound and video already on.

That would indeed be of great help for videoconsultations.
