### ISSUE TITLE
Technical message »DevicesNotFoundError« in emptycontent message

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#263]
Check this out:
![capture du 2017-03-15 19-40-16](https://cloud.githubusercontent.com/assets/925062/23965141/51ba906e-09b7-11e7-8326-c89c5d4114b8.png)

> **Error while accessing microphone & camera**
> DevicesNotFoundError

Instead, because apparently there was a »Devices not found« error, let’s say:

> **Error while accessing microphone & camera**
> Make sure to give the browser permission

Or what is the actual issue?

**Comment by Ivansss** [comment]
> **Error while accessing microphone & camera**

This is the error we show after discarding possible errors caused by permissions or webrtc support. So we don't really know what could be causing the issue.
https://github.com/nextcloud/spreed/blob/d88480378f616282dea526f85adb088639ba7e83/js/webrtc.js#L341


> DevicesNotFoundError

In this case, it seems that the browser could not find any microphone or camera in your device.

We could avoid printing the raw error message/name in the second line of the empty content and instead, print a log in the JS console.

**Comment by jancborchardt** [comment]
> We could avoid printing the raw error message/name in the second line of the empty content and instead, print a log in the JS console.

@Ivansss yes, that would be great. :) There should never be raw error messages or names in the interface.
