### ISSUE TITLE
Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535

### ISSUE THREAD

**Issue by NeutroGe** [nextcloud/spreed#2806]
## Steps to reproduce
1. Install a fresh nextcloud 18.0.0.10 (latest current version)
2. Try to install Talk app
3. Check errors in nextcloud logs

{"reqId":"Xia6aNr0WbUmo-qoephJHQAAANM","level":3,"time":"2020-01-21T08:46:34+00:00","remoteAddr":"xx.xx.85.194","user":"******","app":"PHP","method":"POST","url":"/settings/apps/enable","message":"Cannot declare class OCA\\Talk\\Migration\\Version2000Date20170707093535, because the name is already in use at /var/www/html/nextcloud/apps/spreed/lib/Migration/Version2000Date20170707093535.php#31","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36","version":"18.0.0.10","id":"5e26ba7581626"}

**Operating system**: Centos 8

**Web server:** Apache

**Database:** Maria

**PHP version:** PHP 7.4.1 (cli)

**Nextcloud Version:** 18.0.0.10

Thanks for your help.

**Comment by nickvergessen** [comment]
do you have the spreed in multiple apps/ folders?

**Comment by NeutroGe** [comment]
[root@nextcloud nextcloud]# find /var/www/html -name "spreed"
/var/www/html/nextcloud/apps/spreed
[root@nextcloud nextcloud]#

If that's what you meant :)

**Comment by NeutroGe** [comment]
I've tried again today based on a user reply on nextcloud community forum and found out that it's not a blocking error.

When you install talk, even when there is no spreed folder in the app folder you still get that error, but after getting it you can still press the "activate" button and the app works.

**Comment by nickvergessen** [comment]
Thats even more weird, but okay thanks :)

**Comment by NeutroGe** [comment]
Thanks to you for looking into it :)

**Comment by rubenszolt** [comment]
Hi, On new NC18 I have the same problem, it needed to push 3 times the **Download and Enable** button to make something and then I refresh the page and it appear on Disabled apps category, and at finish it need enabled.

**Comment by AlfredSK** [comment]
Same issue here on a fresh NC 18 installation. There is already an apps/spreed folder but I never installed talk/spreed manually. Maybe it is part of the recommended apps that are installed when the option is set on first run. Ok. Whatever. Let's get rid of it...

`sudo -u www-data ./occ app:remove spreed`

Removal is successful and the folder apps/spreed has vanished. Let's install it again...

`sudo -u www-data ./occ app:install spreed`
...
`PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535, because the name is already in use in /var/www/html/nextcloud/apps/spreed/lib/Migration/Version2000Date20170707093535.php on line 127`

Computer says no. Also, the web interface still shows 'download and enable'.

And now comes the weird part. Hitting 'download and enable' in the web interface again finally enabled Talk. So, somehow it works but there is definitely something wrong.

**Comment by storrgie** [comment]
Similar experience on a fresh NC18 install.

**Comment by nickvergessen** [comment]
Managed to reproduce now

**Comment by fnwbr** [comment]
Just tried this on a fresh 18.0.2 install via docker, still seeing the same error:
```
php occ app:install spreed
PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535, because the name is already in use in /var/www/html/custom_apps/spreed/lib/Migration/Version2000Date20170707093535.php on line 127
```

**Comment by daleosm** [comment]
> Just tried this on a fresh 18.0.2 install via docker, still seeing the same error:
> Me too. Same error.
> ```
> php occ app:install spreed
> PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535, because the name is already in use in /var/www/html/custom_apps/spreed/lib/Migration/Version2000Date20170707093535.php on line 127
> ```

**Comment by nickvergessen** [comment]
Arg... Docker has a custom app path setup?

**Comment by rubenszolt** [comment]
I installed this on a fresh 18.0.2 install, no docker, still seeing the same error:
PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535, because the name is already in use in /var/www/html/custom_apps/spreed/lib/Migration/Version2000Date20170707093535.php on line 127

**Comment by daleosm** [comment]
I must mention that I'm also not using docker and have exact same issue.

**Comment by enoch85** [comment]
This is in the Nextcloud VM as well, which is vanilla Nextcloud. Installing Talk via `occ`

**Comment by nickvergessen** [comment]
Well custom_apps is not vanilla and exactly the tripping point here. But I put it back on my list

**Comment by hacktrick** [comment]
I just had the same error in a docker instance. I _docker execed_ into the container and moved the _spreed_ folder from _custom_apps_ to _apps_ and I'm now seeing Talk inside Nextcloud.

After deactivating and removing the app via Nextcloud and then removing the _apps/spreed_ folder inside the container, I could reinstall the app without problems.

_Talk_ was reinstalled in _custom_apps_ and seems to work.

**Comment by enoch85** [comment]
> custom_apps

I always thought Talk was "default" a Nextcloud app, I stand corrected.

**Comment by nickvergessen** [comment]
Currently no further comments are needed, so I lock this issue for now.

**Comment by nickvergessen** [comment]
WIP: https://github.com/nextcloud/server/pull/20038

**Comment by MichaIng** [comment]
For completness:
- The issue has been reported on the forums as well: https://help.nextcloud.com/t/cannot-install-talk-on-fresh-nextcloud-18-install/68613
- I faced the same with current stable NC18.0.4 on a fresh install when doing: `occ app:install spreed`
