### ISSUE TITLE
Pressing enter again after sending a message sends it again

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/spreed#2853]
## Steps to reproduce
1. Write a message
2. Hit enter so it gets sent
3. In the current room or a different one press enter again in the empty text field

### Expected behaviour
Nothing

### Actual behaviour
The last message gets sent again

**Comment by nickvergessen** [comment]
In our instance which was updated already, or did this happen before this morning?

**Comment by nickvergessen** [comment]
Okay, misbehaves also locally. After some investigation I found:

Adding `this.parsedText = ''` after https://github.com/nextcloud/spreed/blob/e69740b372e17eec4541337b47baa262a5766510/src/components/NewMessageForm/NewMessageForm.vue#L222 makes sure it only works twice. The problem is after reseting the value there, it is immediatelly overwritten again by `contentEditableToParsed`

Looking at AdvancedInputs watcher on text, it shows that text is correctly `''` but
`this.$refs.contentEditable.cloneNode(true)` in https://github.com/nextcloud/spreed/blob/ca12ad093fd523c33a3b2ad4b4307bb1cf54fcb3/src/components/NewMessageForm/AdvancedInput/AdvancedInput.vue#L184 still has the old content.

wrapping that in nextTick solves it, but not sure what the consequences are...
```js
			this.$nextTick(() => {
				this.$emit('update:contentEditable', this.$refs.contentEditable.cloneNode(true))
			})
```
