### ISSUE TITLE
Add occ commands to send message 

### ISSUE THREAD

**Issue by skuizy** [nextcloud/spreed#2866]
Hello,

I have conversation in my talk that I use as a notification system for other apps installed on my server that are basically configured as bots.

As of now, my notification scripts use the web api to send messages. It works great but for security reasons my nginx interface doesn't expose my local network, only my domain name.

I'd like to avoid to send these notification to my ddns for them to come back at my server, it's not pretty and it won't work if my home network goes down, by using an occ command that could work locally.

**Comment by nickvergessen** [comment]
You can also send the messages to "https://localhost" when you configured that as a trusted domain, should work just fine.

An occ command to send messages doesn't make a lot of sense in general, because each user only knows their own conversations, so it would only help in very specific cases like yours. So it is very unlikly this is being focused anytime soon.
