### ISSUE TITLE
ongoing call indicator doesn't always update correctly

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#2947]
I noticed it already a few times on our internal instance that the indicator for ongoing calls doesn't update correctly, e.g. that's how the sales channel looks at the moment in my room list:

![image](https://user-images.githubusercontent.com/1589737/74448566-7dfe8e80-4e7b-11ea-93d2-dc59fb9690bc.png)

But the call was ended 2 days ago. Actually I didn't noticed that the call indicator was there yesterday. If I join the room non of the other participants are online, so there is clearly no ongoing call. But also the button at the top right says "Join call" and not "start call". So for some reasons the status of the room is not up-to-date.

Current Talk version: 8.0.3

**Comment by nickvergessen** [comment]
Yeah, it's triggered by a bug in the android app.
If you join a call and happen to press the back button faster then the join finished, your leave call request reaches the server before the join actually completed (because the android app doesnt wait to send the leave after the join completed).

Ref https://github.com/nextcloud/talk-android/issues/724

The situation should be improved a lot by #2942 I think.
But never the less there seems to be some kind of cleanup reset the users session without resetting the call state.
As a temporary workaround, just go to the conversation, start a call and after everything loaded, leave it again.
