### ISSUE TITLE
Provide the "high performance back-end" for free during Corona outbreak

### ISSUE THREAD

**Issue by rayfun** [nextcloud/spreed#3106]
Currently, more than ever, it's absolutely necessary for people to stay home to avoid spreading the virus further.
Please consider providing the "high performance back-end" of NC Talk for free during this time so people can more easily stay social on a personal/private level for groups of more than 4 people.

Thank you!

**Comment by acs-ferreira** [comment]
This would be hard as it would mean provide code & support. Not a service.

**Comment by HudsonProdigy** [comment]
Yes would be great to have FOSS option for video conferencing during these times. having to rely on zoom and google is not ideal for many people.

**Comment by rkorn86** [comment]
I've already contacted sales team, if it would be possible to just buy HPB solution without the whole Nextcloud enterprise  stuff. We are already using Nextcloud on premise, on a high performance infrastructure, but being limited to 5-6 peers, because of a missing external signaling server solution is very bad these days. We are also willing to pay, but 80 € / user / year is too much for our research centre with > 500 active nextcloud users and > 1200 ldap users.

**Comment by fti7** [comment]
Please make the HPB opensource or integrate Jitsi as a Backend.

I understand the commercial side, but there might be more Enterprise Goodies (Like a good SIP Integration) which would be worth to pay for in an Enterprise Environment.

We currently use Jitsi Meet, which is very nice and scaleable but of course not nicly integrated into Nextcloud

**Comment by gary-kim** [comment]
> Please make the HPB opensource or integrate Jitsi as a Backend.

We will accept PRs (with the promise of maintenance), for support for different signaling servers https://github.com/nextcloud/spreed/issues/2515#issuecomment-598307660. 

The main issue with open sourcing the current HPB is that I don't think Nextcloud GmbH owns it: Struktur AG seems to. From the [website](https://nextcloud.com/talk/):

> The optional Nextcloud Talk High Performance Backend for large organizations by Struktur AG offers the capacity, reliability and features enterprises need to conduct their business privately, securely and efficiently.

That doesn't mean it's impossible for it to happen, the iOS app used to be closed source because it was developed with TWS but it was open sourced later. I just think it's unlikely.

**Disclaimer: I am unaffiliated with Nextcloud GmbH**. I'd also love for an open source signaling server that we could use. 

I'm working on trying to kludge one together from some open source MCU projects and other open source conference systems but I'm not really that good with WebRTC stuff. Anyone want to try this together? :smile:

**Comment by jospoortvliet** [comment]
Hi all,
Sorry, the back-end is simply not ours to give, it is a partner product and they're not willing to do this so that kind of ends the conversation (yes, we've asked).

Luckily there are solutions like Jitsi, we have partners that host the back-end which makes it a LOT cheaper and we're trying to make it doable to have calls with >10 people without the back-end in Talk as well (you can now disable video to drop bandwidth and CPU usage by >20x, so a audio call with 20 ppl should be doable). Hopefully that will all help with this.

**Comment by jospoortvliet** [comment]
As I said, we've asked. And minds have changed, the high-performance back-end isn't just available for free, it is now 100% open source. See more in our blog:
https://nextcloud.com/blog/open-sourcing-talk-back-end-rc-of-talk-9-brings-lots-of-improvements/

**Comment by gary-kim** [comment]
Thank you @jospoortvliet for all you do. It's a hard market and yet you and the rest of the team often do things that are for the community without much monetary benefit.

And thank you to Struktur as well for helping make Nextcloud Talk a viable alternative for many more people by open sourcing the HPB.

> I just think it's unlikely [Struktur AG will open source it]

Guess I got super proven wrong. Thank you so much for that!
