### ISSUE TITLE
Response time always 30s

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/spreed#3163]
I'm monitoring my response times and Spreed is causing my graphics to explose and i really can't understand why... 

See this log entry (from `nginx access.log`):

`GET /ocs/v2.php/apps/spreed/api/v1/signaling/b6nbnzyt HTTP/1.1" 200 - rt=30.622 ut=30.621`

`rt` and `ut` are respectively **R**esponse **T**ime (`nginx`) and **U**pstream Response **T**ime (`php`).

So, **30 seconds**, and these are frequent (thousand of lines like these).
As a result, they are faking (i believe this number doesn't reflect the "real" query time) our monitoring (and every other monitoring i believe):

![image](https://user-images.githubusercontent.com/12234510/77652233-3a18a200-6f6e-11ea-818d-ea1caccd6576.png)

**Comment by nickvergessen** [comment]
They do because we do [Long polling](https://www.pubnub.com/blog/http-long-polling/) for chat messages (and signaling messages) unless you have a [High performance backend](https://nextcloud.com/talk/#scalability) installed.

PHP can not do websockets so there is no other way for a somewhat reliable chat system.
