### ISSUE TITLE
TURN username/password

### ISSUE THREAD

**Issue by rugk** [nextcloud/spreed#331]
In the settings you can only specify a "shared secret". I am, however, used to have a username/password for specifying a TURN server.
See https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/#servers

So maybe change the UI, or so…

**Comment by Ivansss** [comment]
TURN settings are only available for administrators.
The administrator can setup a TURN server with a shared secret and the app will generate credentials (username/password) for every user when needed.

**Comment by rugk** [comment]
Ahh, cannot I use one static username/password without shared secrets?

**Comment by Ivansss** [comment]
That would be a per-user setting. We decided not to add that option because not many people own credentials for a TURN server and some people don't even know what a TURN server is.
So it would be confusing for a normal user to have that option in 'Personal Settings'.
We decided to have TURN settings only for administrators. Then they can setup their own TURN server and every user will be able to use it.

**Comment by rugk** [comment]
Okay
