### ISSUE TITLE
Ringtone for browser users

### ISSUE THREAD

**Issue by Dretech** [nextcloud/spreed#3388]
If you use Talk in the browser you do not hear when someone is calling you. You probably are viewing another tab in your browser, so you don't see that someone is calling. Is it possible to add a ringtone to the web interface of talk when you are logged in in Nextcloud? (If you are using the Android client (and assume IOS client) of Talk you will get a ring tone if someone is calling you using Nextcloud Talk).

**Comment by nickvergessen** [comment]
In most cases browsers prevent automatically playing sound (even on notifications). So when we work on this it won't always work :/

**Comment by Cybnate** [comment]
Supporting ringtone in browser. Discord also does sound notifications so it is possible. And in e.g. Firefox you can mute/unmute each tab separately (right click on tab). Even just a beep is a good starting point. Nothing wrong with user deciding whether they want sound notifications or not.

**Comment by jpbraun** [comment]
I am missing this import feature, too. in Chrome you can mute/unmute each tab separately, too. We need a ring tone, if a user enters the Lobby. Is it possible to contribute for this feature?
Due to the unpredictability of the corona pandemic, our parents have to have the option the call a teacher. For this purpose we are using Nextcloud talk. Without a tone, the teacher will not realize a call.

**Comment by JMLatGitHub** [comment]
This kind of functionality is simply a must for a real-time communication application: There is nothing more annoying than to see that someone is actually available, but the communication attempt does not work because the other person does not even notice the attempt. For me, this lack of functionality is a KO criterion regarding the everyday usability of this application.

Now that Talk offers a lot of interesting features, implementing rock-solid, reliable notifications should be first priority IMHO.
