### ISSUE TITLE
Ability to add description to conversation

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#3432]
I like the Rich workspaces a lot. Maybe it's helpful to add these for every talk room. 
There could be informations about the room stored:
 - Link to our group calendar
 - there are our files stored
 - this is the todo for this week
 - please don't forget our call on wednesday
 - please read before post in this group

**Describe alternatives you've considered**
Pin chat messages to the top where relevant informations are stored would be solve this problem, too.

**Comment by nickvergessen** [comment]
As for linking to the other resources, the Projects tab in the sidebar should help with exactly that.

But yeah some kind of description makes sense too.

**Comment by camilasan** [comment]
More use cases for having a description:
- new employees get added to chats they don't know what it is about, the description would fix that
- public chats can have a link to the code of conduct in the description - generally to avoid conflicts and not polite discussions

**Comment by PVince81** [comment]
We had this topic during the conference on the conference instance: it would have been useful to be able to embed the live stream link and schedule in the main room's description.

### Topics to address during implementation

- only moderators can change the description (the same people who can rename a room)
- ideally links in description should be clickable (if rich content not directly possible)
- need concept for mobile devices as well
- "edit description" action to be close to the description location (and/or in the conversation context menu where the "rename" action is)
- the field update will likely be propagated through the regular channels already (polling of conversation API) just like a name change, so no special channel needed
- extra option in `occ talk:room:update` to be able to update the description with scripts
- optional: same extra option for when creating the room with `occ talk:room:create`

### Questions

1) Where to display the conversation description:
   a) somehow sticky at the top of the chat window
      - pro: directly visible and obvious
      - con: only 1-2 rows, might be a waste of vertical space
   b) in a dedicated right sidebar tab
      - pro: best for space usage
      - con: requires people to go there on purpose
   c) in settings tab
      - pro/cons like b)
      - con: doesn't feel intuitive to go to "settings" to read a description
   d) on top of the right sidebar tabs
      - pro: visible directly
      - con: reduces the available space for the message and require scrolling or an expand button
      - con: would reduce the vertical space for the tab contents like participants

If we'd go the "sticky message" approach instead of "description field", only a) would apply.

other ideas ?

**Comment by nickvergessen** [comment]
We already discussed that it's d) together with a 3 line max and expending on click (like with comments on the files app)

**Comment by nickvergessen** [comment]
- [ ] Plain text with clickable links

**Comment by nickvergessen** [comment]
* Not available for one-to-one and video-verification

**Comment by schiessle** [comment]
It would be also nice if the lobby would show the description. So people see already in advance what is going to happen in a room once the meeting starts

**Comment by ma12-co** [comment]
Good Idea @schiessle :)
