### ISSUE TITLE
Connection to call often fails

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/spreed#3471]
Hello
I have a setup with nextcloud 18.04 and local turn-server. Unfortunately I have often the problem, that I cannot connect to an open call without having an idea why.... While analyzing the debug-log in the browser, there are strange error-messages that are maybe useful for the identification of the source of the problem...see screenshot:

![talk](https://user-images.githubusercontent.com/11720329/81217799-79aac300-8fdd-11ea-94fa-bcbed7e64191.JPG)

Does anybody have an idea, where the problem could come from? Is it a nextcloud-issue or maybe a turn-server issue?

Thanks for your help..
René

**Comment by nickvergessen** [comment]
I guess that is the same as #3439 so I will close it for now.
As per the linked issue it should be better and more responsive in v8.0.9

**Comment by rgl1234** [comment]
Thanks for your feedback....yes, our problems are pretty much the same like those described unter #3439

**Comment by tdm4** [comment]
@rgl1234 Hi.. what happens if you clean out the php sessions (wherever php.ini stores your sessions.. usually it's in file format by default), restart php-fpm (or apache if you're using prefork/mpm) and retrying the call? I've been able to get a call working but needed to clean out php sessions first.
