### ISSUE TITLE
Black borders around video

### ISSUE THREAD

**Issue by username72764274** [nextcloud/spreed#3506]
### Steps to reproduce
1. Do a video call

### Expected behaviour
In past versions, the video of the other participant filled the whole screen.

### Actual behaviour
Since updating to Nextcloud 18, black borders appear at the top, left, and right of the video.

### Browser
Firefox and Chrome

### Talk version
8.08

**Comment by Nyco** [comment]
Agree, Talk doesn't use efficiently the screen estate, even in full screen mode.

When viewing another participant's screensharing, the workaround is to unzoom (browser feature) to grow the content, which is counter intuitive.

**Comment by nickvergessen** [comment]
We are improving there step by step. The black border was chosen because otherwise the other videos could overlap too much of the promoted video.
In the future we will add a button to allow fading out the other videos, which will also make your own video smaller and the promoted video bigger again.

Let's keep this issue around for now to track this as I'm not aware of the solution explained above has an issue already.

**Comment by nickvergessen** [comment]
Ah, it also is linked to this one:
https://github.com/nextcloud/spreed/issues/1341

**Comment by nickvergessen** [comment]
I think this is fixed with the grid view since a while now. Only your own video is not cropped to show you the full background of yours independent from the screen/camera ratio
