### ISSUE TITLE
Upgrade to and Download of Talk 8.0.9 fails with "App with id spreed has invalid signature"

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/spreed#3534]
![grafik](https://user-images.githubusercontent.com/1151915/81838601-9d728980-9546-11ea-9312-f276fcb6fdda.png)

* nextcloud 18.0.4

**Comment by Dubidubiduu** [comment]
Get "An error occured during the request. Unable to proceed. Couldn't update app." when I try to update.

**Comment by Wikinaut** [comment]
Yes. That is the "common message". Look to your Log.

**Comment by nickvergessen** [comment]
So I repackaged v8.0.9 because it was missing the js/ folder on the first go.

Your instance had grabbed the old signature already from the appstore but the downloaded file was the new version already.

So it will "self-heal" if you try after ~5 minutes (refresh rate of the appstore data).

Can you confirm this?

**Comment by simonspa** [comment]
I can confirm, after initial issues it now updated just fine. Thanks! :sparkle:

**Comment by Wikinaut** [comment]
@nickvergessen confirmed, works now. Thanks. Please test before deploying next time.
