### ISSUE TITLE
Screen Sharing Should Be Able To Work Properly With Multi-Monitor Setup

### ISSUE THREAD

**Issue by TakuyaSama** [nextcloud/spreed#3562]
**Is your feature request related to a problem? Please describe.**
Nextcloud Spread doesn't allow to choose what monitor you want to share in a **multi-monitor setup**.

**Describe the solution you'd like**
The option to choose the monitor/screen you want to share.

**Describe alternatives you've considered**
An option to choose what monitor/screen you want to share from the screen it's shown when you click on enable screensharing, to choose the monitor you want to share, if you want to share the entire screen, or the application/tab of the web browser you're using Nextcloud Spread from.

**Additional context**
It's hard to believe IMHO that Nextcloud Spread, being pretty powerful, not limited in general, compared with other alternatives, doesn't allow something that Microsof Skype already does.

I would like to thank you the whole Nextcloud community, devs and non-devs, for the amazing work, software you're creating, giving us such a great software, improving and giving us for free and as FOSS, you really rock.

Bests to everyone ^^.

**Comment by nickvergessen** [comment]
So I get a list from which I can select from, sharing only some:
> ![Peek 2020-05-14 15-40](https://user-images.githubusercontent.com/213943/81941618-598c8c80-95f9-11ea-9d08-425c110ecaf6.gif)

But I'm also unsure if there is much we can do. We just ping [`getUserMedia`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), then the browser offers you the possible selections and we get only the final result.

**Comment by nickvergessen** [comment]
cc @danxuliu

**Comment by sirtoobii** [comment]
@TakuyaSama I assume you are on Linux? Do you have to possibility to test this on a windows machine. According to this Mozilla bugreport https://bugzilla.mozilla.org/show_bug.cgi?id=1037997 it should work on windows. However, on Linux it's an other story:
https://bugzilla.mozilla.org/show_bug.cgi?id=1412333
https://bugzilla.mozilla.org/show_bug.cgi?id=1607238

> doesn't allow something that Microsof Skype already does

Btw skype is a real bummer here: Even on the desktop application you have to use an Xorg session otherwise screen-sharing is impossible. In the browser versions, the same limitations apply as in a nextcloud talk session.

**Comment by nickvergessen** [comment]
Thanks for the links.

As this is nothing we can solve, I will close the issue. Let's hope Firefox 78 (currently assigned version on the issue) will be fixed at some point.
