### ISSUE TITLE
polling the chat with lookintofuture = 1

### ISSUE THREAD

**Issue by pasouf** [nextcloud/spreed#3592]
## Steps to reproduce
1. using python3 requests library

2. using a get query with these :
headers : 
{
    "Accept_Language" : "fr-FR",
    "OCS-APIRequest" : "true"
 }
and params : 
{
    "lookIntoFuture" : "1",
    "timeout" : "60",
    "includeLastKnown" : "1",
}

### Expected behaviour
The get request should wait 60s for a new message to appear, or return the message list when a message appear within the 60s

### Actual behaviour
the get query acts like "lookIntoFuture = 0", and returns a list of the last messages

## Talk app

**Talk app version: 8.0.9** (see apps admin page: `/index.php/settings/apps`)

**Comment by nickvergessen** [comment]
Well you need to specify the last comment you know. Check the API documentation at https://nextcloud-talk.readthedocs.io/en/latest/chat/

Otherwise you will just load the history from the beginning.

**Comment by pasouf** [comment]
I don't get it, the option clearly says "poll and wait" when "lookintofuture" is set to 1, why should I mention the last "known" message ID, how is it useful ? Plus the last message ID cannot be known at the first query.

**Comment by nickvergessen** [comment]
You get the last read message from the conversation list. As a chat client you then load new messages from there and old messages as well into the other direction.
This allows us to have the same query to get new as well as unread messages, so 2 queries are enough in most cases instead of  3 and one of them is empty most of the time.

I get it that it might seem obscure/confusing for a user being new to the api, but for now this is how it works.
We might reconsider this when doing a new api at some point when we also look into webhooks
