### ISSUE TITLE
Are there plans for email notifications for text chats?

### ISSUE THREAD

**Issue by ntnsndr** [nextcloud/spreed#3623]
**Is your feature request related to a problem? Please describe.**
Currently, when I @mention another user in the chat, they don't receive an email notification, and the other users are not on NextCloud frequently enough to be informed that there is a message for them.

**Describe the solution you'd like**
I'd love for NextCloud to send an email notification to users when they are mentioned (or if they are missing chats in a channel they follow).

**Describe alternatives you've considered**
I am hoping to be able to use Talk as a very simple replacement for chat collaboration software. Currently my team uses RocketChat for this, but we would love to be able to do our chat within NextCloud.

**Additional context**
Thanks so much for developing this tool! It has the potential to supercharge our NextCloud toolkit.

**Comment by Dubidubiduu** [comment]
Has been discussed a few times, have a look at #2919 or  #944. I think answer of @daxid https://github.com/nextcloud/spreed/issues/3076#issuecomment-603820684 to @nickvergessen has good points thou.

**Comment by ntnsndr** [comment]
Oh sorry—I tried to look before posting. Thanks. I hope it remains on the roadmap. Until then, Talk won't really be usable for me (in, as @daxid mentions, an academic context).

**Comment by nickvergessen** [comment]
Well as pointed out already in the linked issues:
* Nextcloud has a notification system which should be used for more important stuff
* Nextcloud Talk is using that
* Notification system is missing an email option atm, IIRC there are plans to fix this, subscribe to https://github.com/nextcloud/notifications/issues/314 if you want to get notified
* Talk is not going to work around this

**Comment by Dubidubiduu** [comment]
> 
> 
> Well as pointed out already in the linked issues:
> 
>     * Nextcloud has a notification system which should be used for more important stuff
> 
>     * Nextcloud Talk is using that
> 
>     * Notification system is missing an email option atm, IIRC there are plans to fix this, subscribe to [nextcloud/notifications#314](https://github.com/nextcloud/notifications/issues/314) if you want to get notified
> 
>     * Talk is not going to work around this

Thanks again for replying!!

Here is what I thought before: For me activity and notification was quite similiar, I wasn't really aware of, that there are two different apps for that kind of feedback to the user. Activity already has one spreed setting "Du wurdest zu einer Unterhaltung eingeladen oder hattest einen Anruf" (https://example.de/index.php/settings/user/activity) where I can choose communication via E-Mail or Stream. So I thought sharing an event to this app would be enough and quite simple, since it has be done before by spreed.  So, with this in mind, when saying add e-mail notification it wasn't about notification app (but activity) and it wasn't about adding that functionality to spreed, but hook the activity app.
