### ISSUE TITLE
Reactions in video-call

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/spreed#364]
When using Spreed I have noticed this cool reaction feature. When somebody says something you are able to react with some emojis. Would be nice to have this in video calls ;) 

Emojis used for GitHub comment reactions seem to be good choices 🤔

**Comment by georgehrke** [comment]
Just as a reference how Slack does it:
![](https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2015/07/reaction-examples.png)

[Source](https://thenextweb.com/apps/2015/07/09/how-did-we-ever-live-without-this/)

**Comment by nickvergessen** [comment]
The thing is, the reaction request is about calls (it also is from before we even had chat).
So the idea was to pop the reaction on the black call screen, not respond to a chat message.

**Comment by nickvergessen** [comment]
Maybe you can make that a new/different ticket.

**Comment by georgehrke** [comment]
Yes, let me do that.

**Comment by nimishavijay** [comment]
Great feature! Experimented a bit with what it could look like and this is what we came up with

![image](https://user-images.githubusercontent.com/52440189/230429324-324fb2f9-d0cd-4754-a2b5-a898ca9714e5.gif)

- [ ] The emojis reactions would be accessible from a button in the header
- [ ] The available reactions are: ❤️ 🎉 👏🏽 👍🏽 👎🏽 😂 🤩 🤔 😮 😢 
Any suggestions? 
- [ ] The reaction menu would stay open if you click on any reaction. If you click on anything else on the screen it closes 
- [ ] When you click on a emoji it appears at the bottom of the screen and floats to the top with your full name next to it and fades away. if anyone else reacts it is shown similarly with their name. The color of the name tag could be the avatar color
- [ ] For small screens, the size of this emoji is also small. in the screenshot it is 24px
- [ ] For bigger screens the size could be bigger, around 44px 
- [ ] The logic for animation works like this in the mockup I shared, it could of course be tweaked during implementation:
  - [ ] The total time taken for the emoji to float to the top and disappear is 2000ms 
  - [ ] The total height travelled by the emoji depends on the screen. Generally it should disappear before it reaches the mid point of the screen to not be too distracting. 
  - [ ] The total height can vary by, say, 10% to look more natural. So for example, for a 720px height screen, one emoji would start at the bottom and travel up 200px, while another emoji would travel up 205px, while another one would travel up 190px
  - [ ] The emoji should start fading while it reaches the top. However, it doesn't look right if it starts fading right from the start. So from 0% to 50% of the animation, only the position would change and opacity remains constant. For 50% to 100% of the animation, the position would change as well as the opacity would change from 1 to 0.
  - [ ] For big screens, it can be from 0% to 75% constant opacity and 75% to 100% fading to make sure it remains visible.
  - [ ] The transition is just linear
- [ ]  As discussed, one person can react a maximum of once per 2 seconds
- [ ] If many people are reacting simultaneously, the number of reactions shown on screen must be limited to avoid overcrowding the screen. For small screens, up to 5 reactions can be shown, and for large screen up to 10 reactions can be shown. 


How it could look on big screens:

![image](https://user-images.githubusercontent.com/52440189/230435099-da785c84-198e-49cc-a8b1-053b269d19b8.gif)

Some enhancements for the future:
- Since the number of emojis is limited in case many people are reacting, the video of each person could show the reaction if they are visible in the grid and reacted
- In case of speaker view, the reactions could appear on the outer 2/3 of the call area to avoid crowding the main speaker, for eg. in case there is a screen being shared.

What do you think? Any points of feedback? :) @jancborchardt @marcoambrosini @nickvergessen

**Comment by nickvergessen** [comment]
Implemented via #9249
