### ISSUE TITLE
Special handling of CLI interactions when managing users

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3664]
## Steps to reproduce
1. Add a user via CLI to a conversation (#3465)
2. Chat shows the user was added by an administrator

### Expected behaviour
Clear message that the user was added by an admin

### Actual behaviour
![Bildschirmfoto von 2020-05-25 14-28-54](https://user-images.githubusercontent.com/213943/82812895-43ea5300-9e94-11ea-9219-933030381f9a.png)

cc @PhrozenByte in case you want to look into it, otherwise I might also have a look at some point

**Comment by PhrozenByte** [comment]
Since there's no user session in console the event listener creating the system message sets the initiator to `null` - and Talk interprets this as "Guest added". Can guests actually invite other users? If not we could simply change "Guest added" to "Administrator added". Otherwise I assume that we can somehow check whether the listener is called via console and set a user explicitly... Even though I'm not sure which user we should choose. Or introduce a new `$actorType = "administrator"`? Tricky...

https://github.com/nextcloud/spreed/blob/a56643beb54d99e768067f5c1ca181080eb61e4d/lib/Chat/SystemMessage/Listener.php#L174-L194

https://github.com/nextcloud/spreed/blob/a56643beb54d99e768067f5c1ca181080eb61e4d/lib/Chat/SystemMessage/Listener.php#L248-L271
