### ISSUE TITLE
NC-Talk 8.09, Webinars not working as expected?

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/spreed#3710]
Hello
When I enable the lobby for a webinar, the guest can see the lobby-page correctly. But when the moderator is starting the call, the guests are not joined to the call automatically as I would expect it.....they still see the "lobby"-page

Questions:
> should the Lobby be set to inactive manually, when the webinar started?
> when I set a starting-date/time for the webinar, the Lobby is set to inactive automatically and a page "conversation not available" is displayed to wayting guests....is this the desired behaviour?

Expected behaviour:
> The Lobby-Page should be set to inactive automatically, when a moderator is starting the call

What do you think?
René

**Comment by nickvergessen** [comment]
So we decided against this, to allow moderators to coordinate together before the meeting starts. So If you didn't set the lobby timer, you need to manually remove the lobby in the conversation menu.
Then it should switch from the Lobby page to the chat page after the next sync of the room information. (Worst case 30 seconds due to https://github.com/nextcloud/spreed/issues/2146).

After that they still need to manually join the call, as getting the media permissions etc is nothing we can do automatically.

**Comment by rgl1234** [comment]
thanks...I understand....
