### ISSUE TITLE
Several shortcuts

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/spreed#3741]
There are already some shortcuts available, some functions don't have them yet. Here's an overview including suggestions for the new ones:

- [x] toggle video on/off => <kbd>v</kbd>
- [x] toggle mute/unmute => <kbd>m</kbd>
- [x] toggle fullscreen => <kbd>f</kbd>
- [x] search conversations or users => <kbd>ctrl</kbd> + <kbd>F</kbd>
- [ ] toggle grid/promoted view => <kbd>p</kbd>
- [ ] stop following a promoted person => <kbd>esc</kbd>
- [ ] ~~start screensharing => <kbd>s</kbd>~~
- [ ] ~~leave call => <kbd>ctrl</kbd> + <kbd>space</kbd>~~
- [ ] ~~start call => <kbd>ctrl</kbd>+ <kbd>space</kbd>~~
- [ ] ~~join call => <kbd>ctrl</kbd> + <kbd>space</kbd>~~
- [ ] ~~toggle right sidebar => <kbd>ctrl</kbd> + <kbd>R</kbd>~~
- [ ] ~~toggle left sidebar (conversations overview) => <kbd>ctrl</kbd> + <kbd>L</kbd>~~
- [ ] ~~upload attachment => <kbd>crtl</kbd> + <kbd>U</kbd>~~
- [ ] ~~new conversation => <kbd>ctrl</kbd> + <kbd>+</kbd>~~

Feedback and suggestions welcome.

**Comment by nickvergessen** [comment]
We were just discussing problems of our support system because it is overwriting too many short cuts.

I can see us adding:
* toggle grid/promoted view => <kbd>p</kbd>
* stop following a promoted person => <kbd>esc</kbd>

But for the rest I think we shouldn't do this. Joining/leaving a call is quite crucial, doing that with a keyboard shortcut you were not aware of sounds like a nightmare.
Same for overwriting any other <kbd>ctrl</kbd>+ short cuts which browsers might already have taken over. (e.g. <kbd>ctrl</kbd> + <kbd>r</kbd> reloads the page in mac/safari)

**Comment by nickvergessen** [comment]
And especially when you need to do something afterwards anyway (add conversation name, accept media permissions, select a file, …) I don't think it's worth risking to overwrite users global shortcuts.
