### ISSUE TITLE
First name not shown correctly on invitation box

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/spreed#3888]
## Steps to reproduce
1. Set up NC19 with LDAP and users that have name prefixes (such as Dr. Simon King)
2. Invite them to your chat

### Expected behaviour
The bubble with the first name should appear

### Actual behaviour
the bubble appears, as first name it shows "Dr."
![bug](https://user-images.githubusercontent.com/42836313/86969668-6dbeb700-c16e-11ea-971b-b2700d0ba4c1.png)

I opened up a ticket on server that first name and last name should be pulled as seperate LDAP attributes, see nextcloud/server#21762. This will also help to solve this issue.
## Talk app

**Talk app version:** 9.0.1

## Server configuration

**Nextcloud Version:** 19.0.0

**Comment by nickvergessen** [comment]
Yeah, we are currently just trimming after the first space, which works in most cases I guess but not in all (as shown above).
But adding more fuzzy logic to this is not really going to help in the end. like e.g. in most professional enviroments you actually use last names rather than first names, etc. Names could be duplicate and so on. So I would say if the current way is not working we just fall back to the full name instead.

**Comment by johkoenig** [comment]
I agree that going back to the full display name is probably the best solution.
Larger companies (such as my employer) take efforts to keep the display name unique, for example by adding a location code or a department id to the display name. Just seeing "John" and "Simon" on the list is not sufficient if there are 50.000+ people.
