### ISSUE TITLE
Icon cut of with 2 line names

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#3991]
## Steps to reproduce
1. Join a call with "Marco Ambrosini"
2. Make him share the screen and disable video
3. have more persons in the call so the name goes to two lines

### Expected behaviour
Buttons are okay

### Actual behaviour
Buttons are cut off / too close to the bottom

![Bildschirmfoto von 2020-08-04 14-50-33](https://user-images.githubusercontent.com/213943/89295972-0bb87b00-d662-11ea-9acf-59e371a0f544.png)

**Comment by PVince81** [comment]
strange, I don't see display names any more on master, also not present on Talk 10 with NC 20:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/277525/97022110-02012e00-1554-11eb-98e5-b3d6ad1e47a8.png">

my test users do have display names set

either they have been removed by design or they've gone missing ?

cc @ma12-co

**Comment by PVince81** [comment]
I found some code that refers display name for the call view, so it doesn't look like it was removed by intention.
Raised https://github.com/nextcloud/spreed/issues/4454 to address this

**Comment by PVince81** [comment]
ok just saw the wrapping happening on Talk 10.0.

will retry with master.

**Comment by nickvergessen** [comment]
Name size is now smaller so closing this for now
