### ISSUE TITLE
Allow resizing and disabling own video feed

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/spreed#420]
There's no way to disable my own video(at least on Chromium).

It is way too big by default in my opinion and there is no option to either resize or completely disable it, I'd welcome both.

**Comment by nickvergessen** [comment]
Disabling should be possible, via a little camera icon which is overlaying your own video

As for resizing, I don't know how this could be done...

**Comment by C0rn3j** [comment]
I should have made myself clearer - I do not want to see my own video feed but still actually stream it.

**Comment by irmhild314** [comment]
I want to reinforce the request for resizing and/or moving not only my own, but all video feeds! 
(Not only for a three person call like in #223, but for all kinds of calls.) 

Because I'm deaf and using sign language in the calls, also with my sign language interpreters. So 
(1) it's not useful, that the speakers window always is the biggest and
(2) it's very unfunctional, that the small videos overlays the 'speaking hands' from the big video window. 

If resizing by users isn't possible, I would be very happy with a solution, shows all video call participants in small (same sized) windows, one beside one, without any overlapping and without changing the size automatically.

**Comment by jancborchardt** [comment]
Sorry but if we add resizing or moving we need to test a whole lot of more different scenarios, more than we can do with our current workload already.

@irmhild314 I assume that fixing https://github.com/nextcloud/spreed/issues/223 would resolve the second problem you mention, right?
Would the first one be fixed by for example the ability to "pin" someone to the main view? Either by clicking them, or by having an entry in the 3-dot-menu for example (cc @nickvergessen @Ivansss).

**Comment by irmhild314** [comment]
Yes, I assume, that fixing #223 resolve the second problem. And I'll be very glad, if there are any possibility to pin someone in the main window, especially in combination with the fix of #223. The way to do (clicking, menu entry, ...) doesn't make any difference to me.

**Comment by jancborchardt** [comment]
@irmhild314 ok cool, let’s continue in #223 then. :) I’ll close this issue since we will not implement resizing for reasons I mentioned in https://github.com/nextcloud/spreed/issues/420#issuecomment-350782085

**Comment by C0rn3j** [comment]
@jancborchardt  okay - no resizing - but how about being able to disable your own video feed?

I'm currently working around it by just blocking the frame via Ublock Origin, but that's an ugly workaround.
