### ISSUE TITLE
shortcut for emoji-picker

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/spreed#4271]
**Describe the solution you'd like**

would be nice to not have to click on the icon picker to insert a specific icon.
we could integrate this while we typing text. every icon could have a "name". when you start typing ":xyz" the icon-picker will show all icons which start with "xyz" in the name.

example from a other popular chat solution:
![Bildschirmfoto von 2020-10-03 12-37-33](https://user-images.githubusercontent.com/3705274/94989462-4a40b800-0575-11eb-8e74-1f3923a42aae.png)

**Comment by nickvergessen** [comment]
Cc @PVince81 now there is an issue

**Comment by PVince81** [comment]
at least https://github.com/nextcloud/spreed/pull/4333 should be finished first, then this could be built on top

**Comment by PVince81** [comment]
ref https://github.com/nextcloud/nextcloud-vue/pull/1474

**Comment by ShGKme** [comment]
PR https://github.com/nextcloud/nextcloud-vue/pull/1474 mentioned above is merged. Now `NcRichContenteditable` supports emoji picking with `:`. It also supports mentions with `@`.

Currently `NewMessageForm` in Talk uses its own `AdvancedInput` component based on 3rd-party [vue-at](https://fritx.github.io/vue-at/) lib. **vue-at** adds support for mentions with `@`. And nothing else of rich text is supported now.

At brief glance it seems like `AdvancedInput` could be replaced with [`NcRichContenteditable` from **nextcloud-vue**](https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable):
- It supports `@`-mentioning (and no need of **vue-at** lib)
- It supports emoji-picking with `:` as wanted in this issue
- It has paste event for attachments

In additional we could support and develop only one Rich Text component for all Nextcloud apps. For example, adding basic md-like formatting as discussed in https://github.com/nextcloud/spreed/issues/1027 in future.

What if, instead of adding this functionality to Talk's component, replace it with `NcRichContenteditable`?

**Comment by nickvergessen** [comment]
> What if, instead of adding this functionality to Talk's component, replace it with NcRichContenteditable?

Already on the way:
* https://github.com/nextcloud/spreed/pull/4333

**Comment by marcusquinn** [comment]
2 years 😭 It's the one thing I miss 100 times a day compared to Signal and every single other modern chat app.

❤️ Nextcloud Talk. Please make this happen 😊 🙏

**Comment by ShGKme** [comment]
> 2 years 😭 It's the one thing I miss 100 times a day compared to Signal and every single other modern chat app.
> 
> ❤️ Nextcloud Talk. Please make this happen 😊 🙏

We are working on this, it's on the way :)

**Comment by ShGKme** [comment]
Closed by https://github.com/nextcloud/spreed/pull/4333
