### ISSUE TITLE
Sidebar call regressions

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4574]
## Steps to reproduce
1. Share a file with another user
2. Start a call in the conversation tab
3. Login as the other user in another browesr
4. Start a call there as well

### Expected behaviour
Only a single video visible ? (need to check with older versions)

### Actual behaviour
Two videos visible, the speaker and also the local one.
Following the speaker doesn't seem to work.
It is possible to click on the local video but then there are too many icons:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/277525/98676629-23d42080-235c-11eb-86f1-3015e7b8fe1e.png">

Might be related to recent changes with the grid, collapse mode, etc 

## Talk app

**Talk app version:** 11.0 git master + https://github.com/nextcloud/spreed/pull/4291

@danxuliu FYI

**Comment by PVince81** [comment]
I found other regressions in sidebar view, raised here: https://github.com/nextcloud/spreed/issues/4574

**Comment by danxuliu** [comment]
> Following the speaker doesn't seem to work.

This might be unrelated to the sidebar:
- Open Talk
- Create a public conversation
- Copy the link
- Start a call
- In a private window, open the link
- Join the call
- In any of the windows, follow yourself

The _Stop following_ button will not be properly shown (it will be behind the video button, like in the sidebar screenshot). Moreover, the control buttons will be shown twice, both in your own video and in the main followed video. I guess that in the sidebar the duplicated buttons overlap due to the reduced horizontal space (and there is also [a problem with the placement of your own controls](https://github.com/nextcloud/spreed/issues/4668)).

**Comment by PVince81** [comment]
did you still see this regression when testing ? seeing your screenshot from https://github.com/nextcloud/spreed/issues/4668 seems to show that the overlap problem has disappeared

**Comment by danxuliu** [comment]
> did you still see this regression when testing ?

Yes.

> seeing your screenshot from #4668 seems to show that the overlap problem has disappeared

But in those screenshots the self participant is not being followed, if you follow yourself then the problem appears.

**Comment by PVince81** [comment]
shouldn't the "following" option anyway be removed for the sidebar ? the user doesn't have a way to view all participants so anyway cannot pick one to follow.

I'll verify with 10.0 to see if the regression is about allowing to follow when we shouldn't

**Comment by PVince81** [comment]
right... the bug is about "follow yourself". doesn't make sense to allow that in a sidebar call.
I'll block it.

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/4699

**Comment by PVince81** [comment]
it turns out that the reason for the duplicate controls is that we didn't disable media controls on the followed video, the latter is adressed in https://github.com/nextcloud/spreed/pull/4700
