### ISSUE TITLE
Differenciate unread counters for group mentions and direct mentions

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#4623]
Group mentions and direct mention chips should have different colors.

**Comment by nickvergessen** [comment]
I still totally disagree.

Also in the subject you talk about unread counters and in the description about the mention chips?

**Comment by nickvergessen** [comment]
Also with the upcoming introduction of groups where more a small group you are part of will be mentioned instead of `@all` all the time this should become less and less a problem.

**Comment by ma12-co** [comment]
I don't have super strong opinions on this, I think it could be nice though. cc @jancborchardt

**Comment by jancborchardt** [comment]
Right now, there are several different ways you can get mentioned, and thus a blue notification bubble or not:
1. Direct message in a 1on1 chat: This is obviously important for you as only you will see it
2. @mention in a group chat message: Also important since it’s directed at you, but others might also see it and/or answer, depending on the nature of the message
3. @mention among others in a group chat: Basically same as before, but in this case others are mentioned together with you in the message
4. @all / group mention in a group chat: For everyone in the conversation, with an extra nudge.
5. Just a simple message in a group chat: For everyone in the conversation, nothing extra. This is the only case where the unread bubble will be grey.

By mixing in **4** as visually having the same importance as 1–3 (which are definitely important for you _specifically_), we muddy what it means to be an "important" notification. I’m not saying to just make it grey too, but e.g. just give a blue border instead of making it indistinguishable from a mention specifically to you, creating information overload. (@jenniferpiperek concurred with this when we discussed it at the conference.)

E.g. in GitHub notifications, group mentions are split from mentions which are directed specifically at you, because they are differently important. (Further research would have to be done if we want to know how others do it.)


----

> Also with the upcoming introduction of groups where more a small group you are part of will be mentioned instead of @all all the time this should become less and less a problem.

What do you mean by this actually @nickvergessen?

**Comment by nickvergessen** [comment]
#4324 restructured what a "attendee" is, its not long only users or guests, but (currently) also emails.
Now when you add a group, we can add the group also as an attendee, allowing us to track them and automatically add users to groups based on that, as well as we could do something similar to the guest mentions (`@"guest/sha1(session)`) to mention groups (`@group/engineering`) which would then allow to mention all members of the engineering group with one mention.

**Comment by nickvergessen** [comment]
Backend is in progress at https://github.com/nextcloud/spreed/pull/6193

We are thereby adding a counter for direct mentions (including replies as that is how the notifications work as well).
So when there are unread mentions and:
* the unread mention direct count === 0 => only `@all` mentioned
* otherwise there are N user direct mentions

This should allow the UI to change the style of the unread bubble to use full color (when user was mentioned) or border-color only when `@all` (or group/circle in the future) was used only

No upgrade migration will be done, so on update it will show like you where only `@all` mentioned, but otherwise the upgrade step does not scale (would have to parse potentially thousands of messages).

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/6193#issuecomment-911263698

> Since we can not reset the counter partly when the readmarker is changed, I will convert the API result to a boolean

**Comment by marcoambrosini** [comment]
front-end pr here in the vue components lib **https://github.com/nextcloud/nextcloud-vue/pull/2208**

**Comment by nickvergessen** [comment]
Server API is in, so frontend and mobile apps can start with it
