### ISSUE TITLE
Display Location and Local Time next to each User

### ISSUE THREAD

**Issue by kevATin** [nextcloud/spreed#4657]
Offer more information about users' availability in regards to their current location.

**Proposed additions:**
* Ping/Latency (a simple yet useful indicator to estimate how responsive your communication with that user will be)
* Location (an approximation of their current location, eg: nearby big city, name of their region, or similar)
* Local Time (an indicator that shows the current local time and date, takes into account their timezone, summer/winter time, etc; that way you can quickly guess whether a user is already asleep or can still be reached)

These should all be displayed next to a user's name in the room participants list.
As a user you should have the ability to disable the sharing of these (preferably individually, and per chat room).

**Comment by nickvergessen** [comment]
So I like the idea, but I think this should be generically available in the avatar menu rather then in the side list of talk only.
This would allow the information to be shown everywhere, e.g. deck board comments, sharing, file comments, etc.

The information could be helpful there too. 

But a setting per conversation sounds like over the top.

As for ping/latency I guess it would be nice in calls. The main issue there is that each user could only connect to the HPB and have their connectivity issue there and not with the nextcloud and so on. So that's not so easy and a different storry from the Location/timezone thing above. Mind reporting that in a second issue?
