### ISSUE TITLE
Raised hand not appearing in participant list with HPB

### ISSUE THREAD

**Issue by PVince81** [nextcloud/spreed#4777]
## Steps to reproduce
1. Setup talk app with HPB
2. Setup a call with two peers
3. Click raise hand

### Expected behaviour
Hand appears raised in both video and participant list.

### Actual behaviour
Hand appears raised only in video but not participant list.

## Talk app

**Talk app version:** master

**Custom Signaling server configured:** yes

## Notes

This happens between we assumed that peerId == sessionId which only works with internal signaling.
Need to call a populated getPeer() from the participant store to be able to properly map.

**Comment by PVince81** [comment]
PR here with investigation: https://github.com/nextcloud/spreed/pull/4778

**Comment by schiessle** [comment]
Just wanted to report the same. :slightly_smiling_face: 

Btw, if this is not already the case, it would be nice if all users who raised their hand would be at the top of the participants list in the order of which they raised their hand. The one who raised the hand first at the top. This way the moderator has an easy overview and can make sure that everyone has the opportunity to speak up in the right order.

**Comment by PVince81** [comment]
@schiessle see https://github.com/nextcloud/spreed/issues/4770 for the list sorting.

**Comment by danxuliu** [comment]
When the standalone signaling server is used the peer ID is the signaling sessiond ID, but the participant list is based on the Nextcloud session ID instead. In order to fix this the standalone signaling server has to provide a mapping between Nextcloud sessiond ID and signaling session ID. I will try to take a look at that.

It would be possible to fix this for users by matching the user ID instead of the session. However that would make raised hands to be shown in the sidebar for users but not for guests, which in my opinion would be very confusing. Therefore I think that it is better not to show it for anyone (if the HPB is used) until the needed changes are done.

Also note that `actorId` can not be used to match the participants, as the signaling server relays that property from the clients connecting to it, and if I am not mistaken currently only the SIP bridge provides it. Note that it would not be enough to also provide the `actorId` when the browser connects to the signaling server; the `actorId` is taken into account by the signaling server only when it is provided by an `internal` client (which the browser is not). It might be possible to create an `internal` client by the browser in parallel to the `client` client that it currently uses... but that would be extremely hacky and a can of worms ;-)

**Comment by nickvergessen** [comment]
> It would be possible to fix this for users by matching the user ID instead of the session.

That's a non-solution as it doesn't work for everyone.

> When the standalone signaling server is used the peer ID is the signaling sessiond ID, but the participant list is based on the Nextcloud session ID instead. In order to fix this the standalone signaling server has to provide a mapping between Nextcloud sessiond ID and signaling session ID. I will try to take a look at that.

Well I made an endpoint available that can be used to get the map. Worked fine and was needed to get the mute/speaking state of phone users to work.

> Also note that actorId can not be used to match the participants, as the signaling server relays that property from the clients connecting to it, and if I am not mistaken currently only the SIP bridge provides it.

I think it should always relay all that information and either that or the endpoint which I created is the correct solution. Any other hacking is not a way forward.

**Comment by PVince81** [comment]
> Well I made an endpoint available that can be used to get the map. Worked fine and was needed to get the mute/speaking state of phone users to work.

I checked the result from that endpoint (fetch peers) but the session id returned there did not match the one from WebRTC.
Maybe we are missing up concept of "conversation peer" and "WebRTC peers".
See https://github.com/nextcloud/spreed/pull/4778 for some debug code. @danxuliu

**Comment by PVince81** [comment]
@nickvergessen seems this was fixed with a workaround here https://github.com/nextcloud/spreed/pull/4838/commits/090004f58ae720cf6eef8deb1fbea5a7e0e4aed9

do we want to keep the ticket to investigate a better solution ? maybe a tech debt ticket instead ?

**Comment by nickvergessen** [comment]
Well the "correct" fix will come with daniels syncing of session ids and peer ids. So no further ticket is needed.
