### ISSUE TITLE
iOS app problem

### ISSUE THREAD

**Issue by davidbdeath** [nextcloud/spreed#4930]
I can't connect to NextCloud talk from iOS from the WAN side of my network. I can connect on the local network with the IP address and not the DNS name. I have no problems with the Nextcloud app. I can connect with a computer no problem.

**Comment by nickvergessen** [comment]
Are you talking about calls or in general?

**Comment by davidbdeath** [comment]
in general it wont connect, it says "Nextcloud server not found".

**Comment by Ivansss** [comment]
Does you server fulfill Apple's [ATS requirements](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW57) @davidbdeath?
https://github.com/nextcloud/talk-ios/#prerequisites

**Comment by Spiros-N-Agathos** [comment]
I am a bit desperate. 
How can it be and the iOS Nextcloud talk app works when I am connected in my local WiFi and using the local network address, but if I use the URL of my server does not work? 
1) iOS Nextcloud app works when using the URL.
2) Android Nextcloud talk app works when using the URL.

Is it still because of my self sighed certificate? How can it be and the app works in local network then?

**Comment by nickvergessen** [comment]
Mostlikely you miss a turn server.

**Comment by nickvergessen** [comment]
well it totally depends on the network you are in while testing. But since this is not a general bug in the softwares but a misconfiguration of your server, please search for help in https://help.nextcloud.com/c/support/spreed/52
