### ISSUE TITLE
In fullscreen, neither the call actions menu nor the personal controls menu works, the viewer neither

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/spreed#5027]
In fullscreen, neither the call actions menu nor the personal controls menu works, the viewer neither.

**Comment by PVince81** [comment]
probably a containment issue:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/277525/109305342-dfeb2580-783d-11eb-996a-7ec77f57433b.png">

the popover element is appended into the body but the element we picked for fullscreen is not in that hierarchy

**Comment by PVince81** [comment]
also broken in Talk 10.0.5

**Comment by nickvergessen** [comment]
Also broken in 9
Basically since the menus use the popover and that was moved to the body instead of being in place.
But i think in reset versions the popover menu has an option where to mount it:

https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/Actions/Actions.vue#L297

If we set that to the item we fullscreen it should work again?

**Comment by PVince81** [comment]
yes, that or boundariesElement.

and find a good way to set the main container globally to all vues, like the store or mixins.

**Comment by nickvergessen** [comment]
> yes, that or boundariesElement.

Well additionally maybe, but it needs to "container"ed in the fullscreened element because everything else is not rendered/visible.

> and find a good way to set the main container globally to all vues, like the store or mixins.

Please don't break everything again 🙈

**Comment by PVince81** [comment]
I didn't mean reparenting, only exposing a reusable value to avoid repeating "document.getElementById('content-vue')" everywhere. I noticed that "this.$root.$el" contains that element too but the first time it's evaluated it contains the old element "#content" which gets replaced after Vue finishes it initialization. So not usable in a computed property.

I guess a helper method will do, then, so that this gets reevaluated every time.

**Comment by PVince81** [comment]
- [ ] Actions menu => set `container="#content-vue"` in all relevant occurrences
- [ ] Emoji picker: missing support for container property
- [ ] Avatar: missing support for container property
- [ ] Modal: missing support for container property: https://github.com/nextcloud/nextcloud-vue/blob/v3.6.0/src/components/Modal/Modal.vue#L342

**Comment by PVince81** [comment]
PR for the Actions bit: https://github.com/nextcloud/spreed/pull/5270

others will need more work as they require to extend the nextcloud-vue components...

**Comment by PVince81** [comment]
- [ ] check if some tooltips also need a container

**Comment by PVince81** [comment]
PR for nextcloud-vue to add the container prop: https://github.com/nextcloud/nextcloud-vue/pull/1734

**Comment by PVince81** [comment]
PR for talk app adjustments: https://github.com/nextcloud/spreed/pull/5291

**Comment by PVince81** [comment]
the tooltips are not working either.

adding this `Tooltip.options.defaultContainer = '#content-vue'` in main.js makes it work globally but could potentially affect tooltips in the header.

I've also tried to set that value after switching to fullscreen, but it requires a re-render of the matching components to make it work

**Comment by PVince81** [comment]
all merged, now only the tooltip issue remains

**Comment by PVince81** [comment]
> adding this Tooltip.options.defaultContainer = '#content-vue' in main.js makes it work globally but could potentially affect tooltips in the header.

I've verified that the tooltip default only affects the Talk app by logging inside another app.
More details in my PR: https://github.com/nextcloud/spreed/pull/5488
