### ISSUE TITLE
Can't leave room as $sessionId is null

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#5299]
I was investigating a report about missing notifications in talk-ios (https://github.com/nextcloud/talk-ios/issues/508), although the issue was resolved by the user, I was able to see the same on my NC21,  Talk 11.1 instance.

At the point of my tests, no browser sessions were open, just used talk-ios. I noticed, that the notification was not send, because there was still an active session:
https://github.com/nextcloud/spreed/blob/eb3de685e567aeed2193313402e79cc99c91584d/lib/Chat/Notifier.php#L384-L387

I then looked into talk-ios and the requests, but the DELETE to `/ocs/v2.php/apps/spreed/api/v3/room/{token}/participants/active` was successfully send and also received by the webserver, but the session was still in `oc_talk_sessions`.

After digging around, I found that the `leaveRoom` function was unable to retrieve my session (`$sessionId` was `null`):
https://github.com/nextcloud/spreed/blob/c642f3b889d9d73918945d6aea75b6999c3dbc77/lib/Controller/RoomController.php#L1672-L1685

This only happened with talk-ios to me, not with talk-web. Before splitting Attendees and Session the participant was resolved through the userId, if available:

https://github.com/nextcloud/spreed/blob/32f14e15c4b9330412a12b148b5554f6dd592f9c/lib/Controller/RoomController.php#L1281-L1300

If I use `$participant = $room->getParticipant($this->userId);` it works for me in my test cases.

After reading the comment at https://github.com/nextcloud/spreed/pull/5194#discussion_r585522533 I'm thinking that the TalkSession for the talk-ios request can't be determined, because the request was made on another PHP session? Could there be a bug in leaveRoom?

**Comment by nickvergessen** [comment]
Yeah discussed with @Ivansss already, you need to send the cookies on the leave request and in the future on all requests, esp. Once the iOS app plans to support publicly joined rooms without an account.
The problem is that the cookies are always sent completely instead only the ones for that instance as far as i understood Ivan and that of course is also not acceptable as it would allow an evil admin to log and reuse you cookies to attack any of your other instances
