### ISSUE TITLE
Move »Join call« button to empty content view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#534]
The »Join call« button is basically not visible. It’s unclear that you have to press it to join. Instead the emptycontent view should change to:

> (profile picture)
> Frank is in the call
> [ Join call ]

@nextcloud/talk

**Comment by danxuliu** [comment]
I agree that the _Join call_ button is not visible and that should be improved.

However, the empty content can not be used for that, because (in the near future ;-) ) the chat will be shown in the main view when the user is in a room but not in a call, so the empty content will not be visible.

When the chat is shown in the main view the local video will be removed from there, and it will be added to the main view only during a call. However, it should still be shown somewhere before joining a call to give the user time to "dress up", so the idea was to show a _Preview_ tab in the right sidebar with the local video.

Maybe the _Join call_ button could be shown below the local video in the _Preview_ tab?

**Comment by jancborchardt** [comment]
When someone does start a call, it should show up as if it's a message, in the chat log. "Daniel started a call" with button "Join call". :)

**Comment by danxuliu** [comment]
>  When someone does start a call, it should show up as if it's a message, in the chat log.

Sounds good. But that means that someone else started the call. Where should the button to start the call be shown?

**Comment by jancborchardt** [comment]
Just like Skype in the top right. Let's also do the two icons: Video icon for "Video call" and audio icon for "Voice call". What do you think?

**Comment by nickvergessen** [comment]
There is no "Video call" and "Voice call", there is just "Call".

**Comment by jancborchardt** [comment]
Ok, that's separate anyway. But my other comments stand, about it being in the top right, and as message + button in the chat log.

**Comment by danxuliu** [comment]
>  But my other comments stand, about it being in the top right, and as message + button in the chat log.

I like the idea :-) (although the _message + button_ part may need to wait until we add support for system messages or something like that).

**Comment by danxuliu** [comment]
@jancborchardt Now that the chat view was moved to the main view when there is not an active call, should the _Start/Join call_ button/icon be shown in the top right of the main view, next to the sidebar trigger? And in addition to showing it in the sidebar or instead of showing it in the sidebar?

And where should the _Leave call_ button be shown during a call? Same place or a more prominent one?

Please check https://github.com/nextcloud/spreed/pull/573#issuecomment-357131474 too.

**Comment by nickvergessen** [comment]
I like what skype does for "Join call". They add a black bar at the top (so it really is not missable on the white window) which shows the info with a green button to jump in.

As for leaving maybe next to your own video controlls?

**Comment by jancborchardt** [comment]
Leaving call should be in the same place as join call, whether it is in the sidebar or moves to the header. Having it next to the video controls can cause misclicks and dropped connections.

@danxuliu I answered to the comment you linked, about the header. If we do that, this issue is obsolete I'd say since the "emptycontent" view is chat with header.

**Comment by jancborchardt** [comment]
In the past I think we talked about putting the button _also_ directly in the chat list, when someone else starts a call.

So like:

> Camila started a call
> [ Join call ]

**Comment by stspdotname** [comment]
I use Nextcloud Talk in a project where I am building a laptop for a disabled friend;
see https://www.bsdcan.org/2019/schedule/events/1047.en.html and https://stsp.name/maurice-laptop.html

Maurice and I  did a live video call from Ottawa to Berlin during our presentation of this project at BSDcan 2019. Fortunately, this quite worked well but only because I had another friend in Berlin assisting Maurice with joining the call. We did an initial test call 2 hours before the presentation and it took me quite some time to explain to them that the "small menu icon in the upper right corner with bars and a person on it" needs to be clicked first. Once the big blue "Join call" button was finally visible everything was easy for them. 

I have made an effort to teach Maurice how  to start a call with the current UI but it's just unneccesarily hard on him; using a computer is already difficult enough for him as it is and I'm trying to find ways to make things work without him having to remember all sorts of tiny UI quirks like this (see my talk for reasons why).

Going forward I would like to suggest  Talk as a Skype replacement to Maurice (his laptop cannot run Skype). The idea is that Maurice would be sending a bookmarked shared link hosted on my nextcloud server to friends he wants to chat with. But I am afraid that his friends will likewise have problems joining a nextcloud call. Most them aren't disabled, but I don't expect them to be very computer-literate. Clicking an unimportant looking tiny grey icon on the upper right corner is far from intuitive for most people presented with the UI for the first time.

So we consider this is a usability/accessibility flaw and would love to see it addressed.
I think the above suggestions people have already made are all OK -- just make the blue button visible by default somehow.

Even just having a persistent configuration option to have the sidebar fold out by default when the page is opened that would be good enough for us.

Thanks,
Stefan

**Comment by stspdotname** [comment]
To illustrate the problem more clearly, here are two screenshots.

https://stsp.name/nextcloud-talk-sidebar-hidden.png
This one shows the default UI after a talk has been selected; this is good enough for a text chat but it is unclear how to start a video call.

https://stsp.name/nextcloud-talk-sidebar-visible.png
This one shows the sidebar which only becomes visible after the tiny grey "menu" icon in the upper right corner of the chat window is clicked (which, by the way, also lacks a tooltip on mouse-hover, while the 'fullscreen' icon does have a tooltip).

**Comment by nickvergessen** [comment]
So the actuall issue here is the screen size. Or basically the fact that the window is upscaled for better readability.

**Comment by jancborchardt** [comment]
@nickvergessen kind of – it is that we don’t account for this screen size. Which will also happen if you for example share a call with someone and they open it on a smartphone. :)
