### ISSUE TITLE
SIP configuration

### ISSUE THREAD

**Issue by markkhanippbx** [nextcloud/spreed#5370]
I'm new with Nextcloud talk but I've good experience with SIP based IP-PBX. I'm currently unable to understand how this configuration works.

![image](https://user-images.githubusercontent.com/55556923/111031737-ff09bb80-83d6-11eb-83a9-ab29b47aca4c.png)

I understand the functionality and I love to see it working but some how I'm unable to configure it. Can someone please tell me how it is done.

**Comment by nickvergessen** [comment]
You need the high performance backend of our partner Struktur AG and their adapter from SIP to the HPB.

Maybe we can clarify this on the settings a bit and disable the inputs until a HPB is configured

**Comment by AlexanderProd** [comment]
Is it possible to use SIP with a self hosted HPB?

**Comment by nickvergessen** [comment]
> You need the high performance backend of our partner Struktur AG and their adapter from SIP to the HPB.

self-hosted or not doesn't matter.

**Comment by AlexanderProd** [comment]
> > You need the high performance backend of our partner Struktur AG and their adapter from SIP to the HPB.
> 
> self-hosted or not doesn't matter.

good to know, is the SIP to HPB adapter open source too?

**Comment by lbdroid** [comment]
> is the SIP to HPB adapter open source too?

There doesn't appear to be much in the way of reference to this adapter product at all. I also question whether there is any actual reason to bind it with HPBE to begin -- what does it actually have to do with the HBPE? Just use the same API as talk/spreed and implement a client in something like Asterisk. Then you set up your dial-in with Asterisk, and it makes its connections to spreed.

**Comment by Fuseteam** [comment]
> > is the SIP to HPB adapter open source too?
> 
> There doesn't appear to be much in the way of reference to this adapter product at all. I also question whether there is any actual reason to bind it with HPBE to begin -- what does it actually have to do with the HBPE? Just use the same API as talk/spreed and implement a client in something like Asterisk. Then you set up your dial-in with Asterisk, and it makes its connections to spreed.
> 
> Hmm... looks like asterisk already supports webrtc. This objective might be doable just by plugging together things that already exist.

did you have any luck with that? i meanwhile found this: https://help.nextcloud.com/t/sip-gateway-setup/118109/5

**Comment by Shandeika** [comment]
Hey folks! I've put together a lightweight SIP gateway implementation for Talk. Currently, it only handles outgoing calls from a conference, as we haven't needed incoming calls yet (though PRs are more than welcome!).

We're actively using it in our own setup and it fully covers our main needs. There are a few minor quirks - like a "ghost" guest user lingering after a call - but that seems to be an upstream issue with Talk rather than the gateway (the virtual session itself closes fine).

If you want to take it for a spin or contribute, everything is available in the repo, including a pre-built container: [https://gitlab.shandy.dev/shandy-development/nc-talk-sip-bridge](https://gitlab.shandy.dev/shandy-development/nc-talk-sip-bridge)
