### ISSUE TITLE
Not sent message gets lost if call is ended

### ISSUE THREAD

**Issue by FlexW** [nextcloud/spreed#5372]
## Steps to reproduce
1. Write a message while in a call
2. Don't send that message
3. Someone ends the call
4. Message disappears

### Expected behaviour
The unsent message should not disappear.

### Actual behaviour
Message disappears.

## Talk app

Don't know. The issue appeared on cloud.nextcloud.com

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** ArchLinux

**Browser name:** qutebrowser

**Browser version:** 2.1.0

## Server configuration

**Version:** 21.0.0.8

**Comment by PVince81** [comment]
this is likely because the message form is situated in the sidebar and then gets destroyed when the call ends, and then a new message form gets rendered in the regular message list

as possible solution is storing the currently typed message in the vuex store instead of a local attribute, and reuse/restore it from there when recreating the field

**Comment by nickvergessen** [comment]
But it shouldn't happen unless you are kicked out leave the call yourself

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/spreed/pull/5379
