### ISSUE TITLE
Remove Join call button when starting a call 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#5757]
## Steps to reproduce
1. Start a  call

### Expected behaviour
No join call button is shown

### Actual behaviour
A highlighted join call button is shown in the message list

**Comment by nickvergessen** [comment]
This only happens until your join request is finished. Time matches with the talk team call where you send hundreds of push notifications, so that sounds like it.

But actually https://github.com/nextcloud/spreed/blob/02ab305c66dc1cf9e27e1aa90dc723dfe9c9bded/src/store/participantsStore.js#L308-L312 should make sure to set your inCall state early enough already 🤔

**Comment by nickvergessen** [comment]
this should be fixed since https://github.com/nextcloud/spreed/pull/6507
