### ISSUE TITLE
User status in conversation title is cut by a few pixels

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/spreed#5826]
## Steps to reproduce
1. Start a one to one conversation
2. Make sure the other user is online

### Expected behaviour

User status icon renders fully

### Actual behaviour

![Bildschirmfoto von 2021-06-21 16-11-51](https://user-images.githubusercontent.com/1374172/122776608-89ea3400-d2ab-11eb-99b7-2c31c0eefc40.png)

## Talk app

**Talk app version:** c.nc.com

**Comment by PVince81** [comment]
confirmed

**Comment by PVince81** [comment]
seems the top bar is not designed to fit:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/277525/122782585-22cf7e00-d2b1-11eb-8568-f87f5f47ef00.png">

multiple possibilities:
- change overflow from "clip" to "visible" to make it appear
- or reduce the avatar size to 42px instead of 44px (but then it's less than the standard we use in other places)
- or increase top bar size
- ...

**Comment by nickvergessen** [comment]
We don't reduce the avatar size

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/spreed/pull/5836 which moves the ConversationIcon out of the truncating anchor tag.
