### ISSUE TITLE
Talk breaks the files app

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5858]
## Steps to reproduce
1. Enable talk after https://github.com/nextcloud/spreed/commit/7503ecffaff8faea7effeeb6bd1c0f343ff0d367 (last good 9a7c42baf6dce5eac970b366d7fde3c1ca58f472 )
2. Open the files app
3. Create a folder 
![Bildschirmfoto von 2021-06-23 15-34-20](https://user-images.githubusercontent.com/213943/123105990-89cb6f00-d438-11eb-9685-3d0e896f7f83.png)
4. Reload the page so the folder is there
5. Delete the folder (spinning forever)
![Bildschirmfoto von 2021-06-23 15-35-20](https://user-images.githubusercontent.com/213943/123106143-af587880-d438-11eb-9f6b-548439e20274.png)
6.  Revert the import of `import { uniqueId } from 'lodash'` in https://github.com/nextcloud/spreed/blob/6a3ba91d95a842ff19246a5d5cc7c14314c1f29e/src/components/MessagesList/MessagesList.vue#L81
7. Adjust the usage of uniqueId to a hardcoded value
8. Everything works again

**Comment by PVince81** [comment]
I'm suspecting some kind of library conflict.

lodash does not have `findWhere` but it is used on server. I wonder if there's a place where we're globally replacing underscore with lodash, or merging them somehow in the global `_` symbol.

but I don't see how this import here would trigger that while the other imports don't.

now, in the files app we only import the message list and not all components because of the sidebar tab, so maybe this is the first time we're unlucky to bump against this issue due to lack of lodash usage in that code path. If that's the case, there could be more trouble ahead hidden in the dark...

**Comment by PVince81** [comment]
aha, interesting...

so I've removed the uniqueId thing as you described to repair everything

then in FilesSidebarTab I added `import { isEqual } from 'lodash'` and log the function in beforeMount.
and here the problem happens again

this confirms that the reason we didn't have this issue before once only because of luck.

now, there are other formats for importing, will try them out

**Comment by PVince81** [comment]
PR here with a different style of import that works: https://github.com/nextcloud/spreed/pull/5862
