### ISSUE TITLE
Limit to Groups

### ISSUE THREAD

**Issue by goveacarlos** [nextcloud/spreed#609]
how can i make the app be able to limit to groups on nextcloud 12

**Comment by nickvergessen** [comment]
The problem is, we would need to limit the calling then, or people try to talk/chat/call people which can't even read/access it.

In order to implement this correctly, it adds too much complexity for little benefit.

**Comment by cl4x** [comment]
In my opionion the functionality is very useful.
hint: is it complex to simply enable the icon for the selected groups?

![immagine](https://user-images.githubusercontent.com/47188814/52364930-90631280-2a46-11e9-9708-1c6756ccb87b.png)

![immagine](https://user-images.githubusercontent.com/47188814/52364974-a8d32d00-2a46-11e9-9a4e-e9aebf04198b.png)

**Comment by tobiaslinder** [comment]
We have many clients who are really keen of the talk functionality but we have thousands of users on our nextcloud server 100 different schools and some of this schools are not ready to let their pupils use a platform where they are able to chat. 

In this use case we don't need to limit calling users that are not in permitted groups because we would permit all users of an organisation and they are not going to call users from other organisations.

**Comment by nickvergessen** [comment]
@tobiaslinder in that case, you could get in contact with our sales department about a Talk subscription, to back up the development of this feature:
https://nextcloud.com/enterprise/buy/

**Comment by eutampieri** [comment]
@nickvergessen sorry for commenting on this, but wouldn't be necessary just to limit the search for users in certain groups in order to resolve this?

> The problem is, we would need to limit the calling then, or people try to talk/chat/call people which can't even read/access it.

**Comment by nickvergessen** [comment]
No, but anyway this was fixed with https://github.com/nextcloud/spreed/pull/1585 for 6.0.0
So once you update it is available in the admin settings of the app.
