### ISSUE TITLE
Browser suggests multiple (wrong) Talk conversations for same title

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#6211]
## Steps to reproduce
1. Use Talk a lot with different rooms
2. Open a new tab and type the name of the room you want to join
3. Be confused which to pick

### Expected behaviour
The browser suggestions should be correct.

### Actual behaviour
The same title is shown wrongly for a whole lot of conversation IDs, and only one of those is the correct one. This makes the browser suggestions essentially useless.
This is probably due to loading timing issues, guessing something with Vue setting the title? @marcoambrosini 
![talk url issues](https://user-images.githubusercontent.com/925062/132352594-8c2c2d13-2590-42c5-a40c-77602e83b56e.png)

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu 20.04

**Browser name:** Firefox

**Browser version:** 91.0.2

**Comment by marcoambrosini** [comment]
That's strange, it seems like the token is changing?

**Comment by nickvergessen** [comment]
Maybe the url+title change happen to asynchronously and therefor the new url is saved in the browsers history with the old page title.

**Comment by nickvergessen** [comment]
So not sure, but we change the page title in the before route change:
https://github.com/nextcloud/spreed/blob/f700cbc36bf8192843126af02bdf5ff38b639c42/src/App.vue#L324-L349
https://github.com/nextcloud/spreed/blob/f700cbc36bf8192843126af02bdf5ff38b639c42/src/App.vue#L290-L319

So not sure what could cause this, or it is because of this when the title is saved with the URL at the moment of navigating away (while it already has the new title)

**Comment by jancborchardt** [comment]
This is something I still run into all the time and it really makes it more difficult to join rooms quickly. Proposing for feature planning.
