### ISSUE TITLE
Messages with shared files can not be deleted

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/spreed#6279]
Hi,

when I send a message I can afterwards click on the three dots to open up the context-menu and then click on "delete message".

If i instead click on "share file from files" (sorry if this is not the exact title, but i am not using nextcloud in english so I had to translate it), then there is no "delete message" option in the context menu.

From my point of view this is a bug, as the user should be able to delete those messages too.

**Comment by nickvergessen** [comment]
The problem is we can not easily detect if the file should also be deleted or only unshared etc. This is why it is currently not possible to delete any items that have been shared, but only text messages.

You can jump to the file and unshare the item there

**Comment by xbluemonkx** [comment]
hi,
i neither want to delete nor unshare the file. I just want to delete the message.

I think there are two very easy solutions for this
a) when deleting a message that is referencing a file, you could delete the message and show a popup "please be aware that the file was not deleted and sharing is still active"
b) show a popup so the user can choose to 1) delete message 2) delete message + stop sharing 3) delete message + delete file

**Comment by nickvergessen** [comment]
> when deleting a message that is referencing a file, you could delete the message and show a popup "please be aware that the file was not deleted and sharing is still active"

This is really cumbersum for the people especially if they have hundreds of files shared

> show a popup so the user can choose to 1) delete message 2) delete message + stop sharing 3) delete message + delete file

While this can then do all of the things it's also a bit overwhelming.
Also it could be that the user can not delete the file but just unshare it (could be shared with them without delete permissions, etc) which makes the dialog also rather complicated to create because that information is not available when reading the message.

> I think this should be converted to a feature request then

I thought there was already, but I couldn't find one anymore
