### ISSUE TITLE
Talk settings: cannot remove/clear STUN server input field in the settings

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/spreed#642]
## Steps to reproduce
1. go to <your-nextcloud>/index.php/settings/admin/talk
2. enter something into the STUN server field, let it be saved
3. click the trashcan icon beside the STUN server field

### Expected behaviour
The STUN server entry should be removed, the field should be cleared (same as it works with the TURN input field)

### Actual behaviour
The field does not get cleared. Instead a default value "stun.nextcloud.com:443" is being set here.
When I clear the text from the input field, the field gets marked red as invalid, so it doesn't save this way either.

![image](https://user-images.githubusercontent.com/295122/35967973-ce13231a-0cc2-11e8-85a2-6a7c27548ff2.png)

## Browser

Opera

NC 13, Talk app 3.0.1

**Comment by mathiasconradt** [comment]
@Ivansss explained that we set stun.nextcloud.com as default if the user doesn't provide one - makes sense. Just from a UI perspective, without explanation, a user might not understand why he cannot remove this one entry.

So, we could allow a user to remove the entry, same as TURN, and then just keep the logic in the background: if there is no STUN entry, use stun.nextcloud.com, if there is an entry, don't use the fallback.
This might be less confusing. 
Or if it's not an option, cause we want to be transparent that something goes out to stun.nextcloud.com server, it should be explained with some description on the settings page.

**Comment by r2evans** [comment]
@mathiasconradt, I disagree with the suggestion to use `stun.nextcloud.com` if nothing is configured; this is precisely the type of behavior (an unsolicited phone-home) that is "scary" in so many apps. I am learning that STUN is a *requirement* for talk, so I suggest a better path is to state clearly that a STUN server is required instead of silently disallowing an empty field. Please no hidden default remote server!

It would be even better if the message that says "at least on STUN server is required" would also contain a link to more discussion about the subject. For instance (and I'm researching this now for myself), what are the implications of using `stun.nextcloud.com` in place of an in-house STUN server (e.g., coturn) in the context of performance and privacy.

Side question: is STUN really required for WebRTC? For instance, if there's an internal-only instance of nextcloud/talk where all IPs are visible (no NAT), is STUN necessary? If this is true, then there should be a mechanism for clearing this field and electing "no STUN server", even if an "advanced guru configuration".

**Comment by mathiasconradt** [comment]
@r2evans I totally agree with you. 
I will leave it up to the product managers/engineers to decide though. In any way, it's important to clarify/inform the user in some way.

**Comment by r2evans** [comment]
Actually, with my research, it seems that STUN is only required if the webrtc node (nextcloud) is behind a NAT. If it is on a public IP, I believe STUN/TURN are not required. This is confusing, since I would have assumed that it is made mandatory in nextcloud for a technical reason and not an assumption of use.

(Please, somebody correct me if I am interpreting the STUN docs incorrectly.)

**Comment by Ivansss** [comment]
Hi @r2evans ,
The STUN server is used by the clients to find out their public address (like _whatsmyip_ service).
Without a STUN server, only clients connected to the same network will be able to connect to each other, because they would only know their local/private addresses.
So in theory STUN is not required, but it's needed in most cases. That's why we decided to provide one by default.
TURN servers are needed by clients behind a symmetric NAT.
When a TURN server is used by a client, all the communication is relayed to this server. That's why we don't provide one by default and we let admins to configure their own.

**Comment by r2evans** [comment]
Ok, so I misunderstood, thank you @Ivansss.

I recognize the nextcloud is unlikely to want to include a full STUN server with the server, so there needs to be some functional capability on initial installation. However, relying on `stun.nextcloud.com` seems to diverge slightly from *"Protect, control and monitor data and communication in your company"*, a nextcloud byline.

In concert with the theme of privacy protection, I suggest that NextCloud's privacy policy be expanded to address the use of STUN within Talk. Though I don't know enough of the protocol internals, I believe the most that is leaked is some basic information about the client's network environment (IP address), I may be wrong ... which suggests that somebody more adept really should summarize what is being leaked, what is being used (two different things), and if necessary a link to coturn so that the user can figure out how to side-step that data leak.

**Comment by nickvergessen** [comment]
I added a notification: `You deleted all stun servers. Because a stun is necessary in almost all cases, we added a default stun server.`
