### ISSUE TITLE
Blur-free area does not grow to HD?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6593]
## Steps to reproduce
1. Have a HD/full HD camera
2. Enable video + blur
3. Open console and run:
```js
OCA.Talk.SimpleWebRTC.webrtc._virtualBackground.getInputTrack().applyConstraints({ width: 640, height: 480 })
OCA.Talk.SimpleWebRTC.webrtc._virtualBackground.getInputTrack().applyConstraints({ width: 960, height: 720 })
```

### Expected behaviour
blurring works as expected

### Actual behaviour
640*480 | 960*720
---|---
![Bildschirmfoto von 2021-11-23 10-35-27](https://user-images.githubusercontent.com/213943/143000964-87c42a1b-93d1-4abb-883b-93ee46246238.png) | ![Bildschirmfoto von 2021-11-23 10-35-20](https://user-images.githubusercontent.com/213943/143000969-50b039c4-c6ec-4612-8c8c-345bbeecd895.png)

Tell us what happens instead

## Talk app

**Talk app version:** 13.0.0-rc.3

**Custom Signaling server configured:** c.nc.c

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Ubuntu

**Browser name:** Chromium

**Browser version:** 96

**Comment by danxuliu** [comment]
This should be (indirectly) fixed by #6591.

Before #6591 the canvas size was got [from the input stream](https://github.com/nextcloud/spreed/blob/v13.0.0-rc.3/src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js#L157-L162), but the segmentation mask [was drawn](https://github.com/nextcloud/spreed/blob/v13.0.0-rc.3/src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js#L177-L187) using [the size set when `updateInputStream()` was called](https://github.com/nextcloud/spreed/blob/v13.0.0-rc.3/src/utils/media/effects/virtual-background/JitsiStreamBackgroundEffect.js#L368-L369). This method is called when the track constraints are changed using the TrackConstrainer node (for example, when the quality is changed in a call with several participants), but it is not if the constraints are directly applied on the track. Therefore, the output canvas was using the updated sized, while the segmentation mask was drawn with the original size.

With #6591 the size for both the output canvas and the drawn segmentation mask is got from the input video element, so they are the same even if `applyConstraints()` is called directly without using the `TrackConstrainer` node.
