### ISSUE TITLE
Improve label of the audio button "No audio"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6608]
Currently the label of the audio button says "No audio" maybe we should change that to "No audio device selected" or something a like and clicking it could bring up the device checker?

(Something for a follow up thou)

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/6604#issuecomment-978950745_

**Comment by anniemichel** [comment]
Hi, could I work on this?

**Comment by nickvergessen** [comment]
Sure. Do you need more pointers to the code?

**Comment by anniemichel** [comment]
Yeah, that would be great. Thank you!

**Comment by nickvergessen** [comment]
Code should be here:
https://github.com/nextcloud/spreed/blob/02e83a61dc246c3130a6ed8bd2e969996b96d0b8/src/components/CallView/shared/LocalMediaControls.vue#L389-L419

Not sure how to trigger the device checker from there thou

**Comment by anniemichel** [comment]
Thank you!
Would you be able to advise me in how I should go about setting up the development environment? I see that I need to install a Nextcloud server in order to clone the repo, but I'm confused about how to do that on MacOS. Do I sign up at a provider and install a server through Nextcloud's website, or do I need to follow a different development setup?

**Comment by nickvergessen** [comment]
I'd recommend to use https://github.com/juliushaertl/nextcloud-docker-dev
