### ISSUE TITLE
new voice message hard to recognize

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/spreed#6621]
voice message is not bold:
![image](https://user-images.githubusercontent.com/24530680/143491044-e47b1fcc-3dff-4e27-897b-320a8fa13ecc.png)

text is bold:
![image](https://user-images.githubusercontent.com/24530680/143491090-e6d2311c-db9f-48a4-ae76-6c9075a6c118.png)

attachment is bold:
![image](https://user-images.githubusercontent.com/24530680/143491175-36b3f134-e144-45b5-bebf-2d26a61894fb.png)

**Comment by nickvergessen** [comment]
Noticed that too... It's for all attachments which is actually not desired anymore i think

**Comment by nickvergessen** [comment]
The problem is https://github.com/nextcloud/spreed/blob/6a648a9ae96c5892a1285a96bb5d0f2bba842672/lib/Chat/ChatManager.php#L361-L364 which only looks out for `comments`, but shares are "system" with `message` "{"message":"file_shared",…"
so it's hard to make a query like that.
Maybe we need to use a different verb for the shares where we want the status (at least on DB level) so we can later on count them with a simple query

**Comment by nickvergessen** [comment]
Also would be nice to extend the comments manager to be able to give an array of verbs to check for

**Comment by nickvergessen** [comment]
Also noticed while doing that, the UI is not marking the messages read if there is no comment afterwards. You can only move the read marker below it with the "Mark conversation read" feature in the left sidebar

**Comment by nickvergessen** [comment]
> Also would be nice to extend the comments manager to be able to give an array of verbs to check for

PR in https://github.com/nextcloud/server/pull/29921
