### ISSUE TITLE
Include chat metadata in unified search entry

### ISSUE THREAD

**Issue by thisIsTheFoxe** [nextcloud/spreed#6723]
**Is your feature request related to a problem? Please describe.**
Implementing unified search on clients as it is now requires parsing the `{ "entries": [ { "resourceUrl": ... ` to get the relevant data. This is a very unclean solution.

**Describe the solution you'd like**
As was mentioned in 2nd the linked issue, the files provider uses the `attributes` key to provide additional metadata. A similar approach could be used here, where `roomToken` would be the most important, but other info could be useful as well.
Example: `> http://localhost/ocs/v2.php/search/providers/talk-message/search?format=json&term=test`
```json
"entries": [
  {
    "thumbnailUrl": "http://localhost/avatar/admin/64",
    "title": "admin in Test",
    "subline": "test message",
    "resourceUrl": "http://localhost/call/abc123#message_42",
    "icon": "icon-talk",
    "rounded": true,
    "attributes": {
      "roomName": "Test" 
      "roomToken": "abc123",
      "messageId": 42,
      "sentBy": "admin",
      "timestamp": "2021-12-17"
    }
  }
]
```

**Describe alternatives you've considered**
As said, the only other solution I see is parsing the url manually.

**Additional context**
- https://github.com/nextcloud/ios/issues/1571
- https://github.com/nextcloud/files_fulltextsearch/issues/143

**Comment by nickvergessen** [comment]
Interesting, I was not aware of the attributes thing as it was not used in the core at the time of implementation:
https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/public/Search/SearchResultEntry.php#L115-L126

Code to adjust is:
https://github.com/nextcloud/spreed/blob/52eb2fdee97e24f23232550c2b8a031f497514d8/lib/Search/MessageSearch.php#L209-L220

In order to not have too many unused attributes exposed which we can never remove/modify, let's only add:
```json
{
    "conversation": "token",
    "messageId": 42
}
```

For now?

**Comment by thisIsTheFoxe** [comment]
@nickvergessen sounds great, thanks for the fast response!
