### ISSUE TITLE
Add useful information to the top-bar when in a call

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#6766]
Counter of people and elapsed time (possibly with conversation info too, as it shows in the chat view)

ref #6696 

EDIT by @jancborchardt:

**Is your feature request related to a problem? Please describe.**
When in a conversation, the description is nice and present. If there is a link to meeting notes or something like that, it’s easy to find.
As soon as you join the call though – the moment when you actually need the meeting notes – the description is only reachable via the menu anymore.

**Describe the solution you'd like**
For there to be a header as well during the call, for example. The navigation toggle and buttons on top right stay anyway, so the title and description could also stay where they are.
@marcoambrosini since I’m sure we either talked about this before or you thought about this. :)

**Additional context**
In conversation (description shows nicely):
![image](https://user-images.githubusercontent.com/925062/176631753-557a3c7c-aafe-41e9-a268-0504eac0faaa.png)

During call (unsure where to find description):
![image](https://user-images.githubusercontent.com/925062/176631167-915c9339-406c-4023-b93d-2d94f85557c1.png)

**Comment by ChristophWurst** [comment]
A personal real-world use case.

I called someone in a 1-1 room today for a meeting. The other person didn't pick up right away despite the scheduled call and so I thought that they might be out of office or something. So I looked at the top left, where I usually find the status, but there is nothing:

![Bildschirmfoto vom 2022-09-19 15-15-53](https://user-images.githubusercontent.com/1374172/191027374-52a38217-69e5-4f9b-8310-99e514b28049.png)

For this use case it would have been helpful if I still see the same status as outside of a call so that I get a hint about the availability of the other person.

**Comment by jancborchardt** [comment]
@nickvergessen I’d like to propose this for next planning evaluation – I notice that in every single call which has notes linked in the description. :)

**Comment by nickvergessen** [comment]
As mentioned in another call we are going to extend the top bar a bit. The idea is to show:

* ⏺️ A recording icon when the call is being recorded
* ⏱️ The current duration of the current call
* 👥 The number of call participants (I only recall this but couldn't find it in the docs/notes)
* 🏷️ The description

**Comment by marcoambrosini** [comment]
done in #8341
