### ISSUE TITLE
Since update to Firefox 96 I don't receive any video streams and screenshares

### ISSUE THREAD

**Issue by schiessle** [nextcloud/spreed#6802]
Happens on c.nc.com

Since my system updated to Firefox 96 I no longer receive video streams from other participants or screenshares. I just see a dark gray area, the default background from talk.

The other direction works fine, my video and screenshare gets transmitted to the recipients.

Are you aware of any issues with Firefox 96?

**Comment by nickvergessen** [comment]
Can not reproduce. Works pretty fine here, from iOS to FF96 and from one FF96 to another FF96.

Anything in your browser console maybe? Does it work with another browser from your network?

**Comment by schiessle** [comment]
Yesterday it worked fine and today it is broken again :(

That's what I see in the browser console:

````
Simulcast stream not changed 
Object { id: Getter & Setter, parent: Getter & Setter, type: Getter & Setter, oneway: Getter & Setter, sharemyscreen: Getter & Setter, stream: Getter & Setter, sendVideoIfAvailable: Getter & Setter, enableDataChannels: Getter & Setter, enableSimulcast: Getter & Setter, maxBitrates: Getter & Setter, … }
​
__ob__: Object { value: {…}, dep: {…}, vmCount: 0 }
​
_initialStreamSetup: 
​
_pendingReplaceTracksQueue: 
​
_processPendingReplaceTracksPromise: 
​
callbacks: 
​
channels: 
​
check_audio_interval: null
​
check_video_interval: null
​
enableDataChannels: 
​
enableSimulcast: 
​
id: 
​
logger: 
​
maxBitrates: 
​
nick: undefined
​
oneway: 
​
parent: 
​
pc: 
​
pendingDCMessages: 
​
receiveMedia: 
​
sendVideoIfAvailable: 
​
sharemyscreen: 
​
sid: 
​
stream: 
​
substream: 2
​
temporal: 2
​
type: 
​
<get _initialStreamSetup()>: function get()
​
<set _initialStreamSetup()>: function set(e)
​
<get _pendingReplaceTracksQueue()>: function get()
​
<set _pendingReplaceTracksQueue()>: function set(e)
​
<get _processPendingReplaceTracksPromise()>: function get()
​
<set _processPendingReplaceTracksPromise()>: function set(e)
​
<get callbacks()>: function get()
​
<set callbacks()>: function set(e)
​
<get channels()>: function get()
​
<set channels()>: function set(e)
​
<get enableDataChannels()>: function get()
​
<set enableDataChannels()>: function set(e)
​
<get enableSimulcast()>: function get()
​
<set enableSimulcast()>: function set(e)
​
<get id()>: function get()
​
<set id()>: function set(e)
​
<get logger()>: function get()
​
<set logger()>: function set(e)
​
<get maxBitrates()>: function get()
​
<set maxBitrates()>: function set(e)
​
<get oneway()>: function get()
​
<set oneway()>: function set(e)
​
<get parent()>: function get()
​
<set parent()>: function set(e)
​
<get pc()>: function get()
​
<set pc()>: function set(e)
​
<get pendingDCMessages()>: function get()
​
<set pendingDCMessages()>: function set(e)
​
<get receiveMedia()>: function get()
​
<set receiveMedia()>: function set(e)
​
<get sendVideoIfAvailable()>: function get()
​
<set sendVideoIfAvailable()>: function set(e)
​
<get sharemyscreen()>: function get()
​
<set sharemyscreen()>: function set(e)
​
<get sid()>: function get()
​
<set sid()>: function set(e)
​
<get stream()>: function get()
​
<set stream()>: function set(e)
​
<get type()>: function get()
​
<set type()>: function set(e)
​
<prototype>: Object { offer: offer(t), handleOffer: handleOffer(t), answer: answer(), … }
 2 2 peer.js:457:2

````

**Comment by rfc2822** [comment]
Here we have the same problem from time to time with Firefox and Nextcloud 23.0.0 with Talk and HPB. It always helps to completely close Firefox and start the call again.

**Comment by danxuliu** [comment]
> cc @danxuliu there are more and more mentions of "I have to reload to hear/see people/screenshares"

In [Firefox 96](https://www.mozilla.org/en-US/firefox/96.0/releasenotes/) there were some changes to the inner parts of WebRTC, like updating the library and some video related fixes. I am not aware of any change that should require adjusting the apps, though. But these problems could be regressions in Firefox itself; see, for example, https://bugzilla.mozilla.org/show_bug.cgi?id=1755609

**Comment by rfc2822** [comment]
> It happens for me still randomly. If it happens it helps to leave the call, reload the page and join again. Talk runs in a pinned tab for me the whole day, so I wonder if something happens when the tab is inactive for to long?

Happens here (on my collegue's PC) directly after booting the PC & joining a chat, no inactive tabs before for long time.

Switching between Talk channels and incorrect handover might be possibly related.

**Comment by nickvergessen** [comment]
Recent problems with Firefox are popping up more and more.
Some people always have to rejoin their first call of the day in order to be able to see screenshares and videos.

Should really try to find out what's going on there.

**Comment by danxuliu** [comment]
Finally I had it myself and could investigate it. As previously mentioned it looks like an issue in Firefox rather than Talk (and apparently there is no work around that could be applied in Talk either).

I joined a call and I could not see the video of other participants. After that call I started a different one and joined it from a private window in Firefox and from Chromium. In the private window and Chromium I could see each other videos, but in the original window I could not see any video. I joined the call from a different tab in the original window and I could also see the other videos. The problem was therefore specific to the tab were it first happened. Leaving and joining the call made no difference, but the problem was gone once I reloaded the tab.

The `inbound-rtp` stats of the received video showed that the video was being received and decoded. However, `frameHeight` and `frameWidth` were both `0`. I tried to force the sending of a full frame to check if that could reset the video and make it work, but unfortunately I was not able to; only `pliCount` was increased, but not `firCount`. Nevertheless, it would be strange if that worked, and it would not be a solution as it can not be forced from an API.

The problem was specific to video tracks coming from RTCPeerConnections; if a video track captured from a canvas was set as the source of a video element it worked as expected. Similarly, setting a remote stream from an RTCPeerConnection that had both audio and video caused the audio to be played, even if the video was still empty.

I also established a direct RTCPeerConnection with other browser, without going through Janus, and the problem persisted. I also forced the video codec to H.264 to see if the problem could be related to VP8, but again the problem persisted.

There is still the question of whether all this is randomly triggered by some specific code in Talk, but even in that case the problem would be something internal in Firefox that should not happen.

**Comment by nickvergessen** [comment]
So close @danxuliu ?

**Comment by danxuliu** [comment]
> So close @danxuliu ?

Yes, I think that the problem is an internal regression in Firefox rather than a Talk issue.

> I still have the problem with newest Firefox... should I create a report at Firefox instead of this one?

That would be great, thanks a lot!
