### ISSUE TITLE
"signaling_mode=internal" entry on oc_appconfig bypass signaling server config

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/spreed#6811]
## Steps to reproduce
1. Configure and deploy a HPB server
2. Configure Nextcloud talk to use this HPB => all is green
3. The HPB is not used at all

### Expected behaviour
The talk config page should say something is wrong

### Actual behaviour
All seem to be OK on the Talk config page, but when starting a call, there is no noticeable difference with a call without HPB. No network traffic can reach the HPB.

## Talk app

**Talk app version:** 13.0.1

**Custom Signaling server configured:** yes ! 

**Custom TURN server configured:** yes !

**Custom STUN server configured:** yes !

**Solution :** there was an (old ?) entry in the database on table oc_appconfig named signaling_mode, with the value "internal". This hidden entry bypass all the signaling server config without warning the administrator. I think it's related with this line of code in public function getSignalingMode of spreed Config.php : 

`$mode = $this->config->getAppValue('spreed', 'signaling_mode', null);`

But we couldn't find an interface to see or change the value of this entry in the database. We had to compare with other Nextcloud instances to see it (after weeks of incomprehensible failed tests :/ ) and simply remove the database entry.

**Comment by nickvergessen** [comment]
yeah that is the whole point of the config. Defining the mode.
It's like setting up a redis server and then note having redis selected as caching backend in Nextcloud.

Deleting it is save.

I checked the code and the only place where it is set automatically is when you did the HPB trial.
I guess we should fix that to not set the config at all, so it uses the default way to determinate the mode: when a server is defined "external" otherwise "internal"

**Comment by Mer0me** [comment]
Yep, we did the HPB trial on this one. It's probably the cause of the problem.
