### ISSUE TITLE
📲 Add controller URL which opens directly the call/device checker

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7038]
> * which opens browser and joins call

is this possible to directly join?

_Originally posted by @tobiasKaminsky in https://github.com/nextcloud/desktop/issues/4159#issuecomment-1070774081_

**Comment by tobiasKaminsky** [comment]
Current notification already has a "join call" action.
You can simply use the url there.
Once this is implemented the url "just" changes on server side and directly joins call. 

![image](https://user-images.githubusercontent.com/5836855/160870186-a76519b6-1923-4bc2-a550-0e7009232244.png)

**Comment by Antreesy** [comment]
After clarification call with Joas:
- this is not going to be a new entrypoint (for creating an embedded window in Desktop client, for example)
- notification link will be modified to contain a flag for direct opening of call (like `../call/{token}?direct_call`)
- navigating to this link will immediately shows MediaSettings dialog
- optionally, forceJoinCall may be used to mount a CallView instead of  ChatView (as we assuming that person wants to join call)

**Comment by nickvergessen** [comment]
> forceJoinCall may be used to mount a CallView instead of  ChatView (as we assuming that person wants to join call) 

As mentioned I don't think this is a good idea. If you had camera on last time and clicked away the media settings modal for ever, we would expose the user with camera and audio after following a link in an email and alike, so should require a confirmation via the media settings screen
