### ISSUE TITLE
Insert tooltip in left sidebar component

### ISSUE THREAD

**Issue by mstolf** [nextcloud/spreed#7300]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
Currently, when a user has a very long name, the name of the user is partially cut to fit inside the component, so it is not possible to read the full name of the user.

**Describe the solution you'd like**
Include tooltip in left sidebar when hovering over username

**Additional context**

**Comment by carlcsaposs** [comment]
I tried implementing this but I ran into an issue where the tooltip would extend off the screen.
![image](https://user-images.githubusercontent.com/97926121/169629233-a56285f7-f9bb-4fcf-9326-9e831458e180.png)

Here's a branch that adds a `titleTooltip` prop to the `ListItem` component, in case anyone finds it useful: https://github.com/nextcloud/nextcloud-vue/compare/master...carlcsaposs:title-tooltip.

I saw an issue (https://github.com/Akryum/floating-vue/issues/175) about the tooltip having a fixed width.  I was unsuccessful in trying to change the width of the tooltip using the selector in the linked issue.  I tried `::v-deep` in src/components/LeftSidebar/ConversationsList/Conversation.vue but I'm not sure if that was the right place.

I also tried changing the placement of the tooltip but that didn't prevent the tooltip from getting cut off.

**Comment by nickvergessen** [comment]
@marcoambrosini can you try to assist?

**Comment by marcoambrosini** [comment]
@carlcsaposs it seems that the boundaries element for the tooltip is not defined. Could you try and pass in an options object like in the example below adding a boundaryElement key to the object? 

<img width="402" alt="Screenshot 2022-05-26 at 15 12 11" src="https://user-images.githubusercontent.com/26852655/170494450-11029fd3-35d8-4d86-b903-ca55143eee85.png">

**Comment by carlcsaposs** [comment]
@marcoambrosini Thank you!  I was able to prevent the tooltip from extending off the screen with a few different options key-value pairs.

Are any of these pairs acceptable?

1. `boundariesElement` set to `#content-vue`
![content-boundary](https://user-images.githubusercontent.com/97926121/170563745-bd4b6a7c-c442-408a-8213-ffbd4762feae.png)
2. `container` set to `false` (uses parent html node)
![false-container](https://user-images.githubusercontent.com/97926121/170564301-8275589e-41de-45db-9d42-78a6d0f21031.png)
3. `container` set to `#app-navigation-vue`--notice padding
![navigation-container](https://user-images.githubusercontent.com/97926121/170564332-b5586c52-29f4-49b8-b207-5f2cdb7bcd8a.png)

Setting `boundariesElement` to `#app-navigation-vue` did not prevent the tooltip from extending off the screen.

-----
Also, I'm noticing that, when "un-hovering", the tooltip disappears slightly after the `ListItem` actions, which causes the tooltip to shift to the right slightly for a moment.

I noticed that the [tooltip directive has been modified to have a hide delay](https://github.com/nextcloud/nextcloud-vue/blob/3d6b4ebdf096ab9d82da020d2a6dac885760d04a/src/directives/Tooltip/index.js#L32) and I was wondering if this tooltip should have that same delay & shift to the right slightly for that delay.

If not, I tried setting the delay to 0 but the shift was still present, just much shorter.

Before setting the delay to 0, my initial thought was to bind the `hovered` status of `ListItem` to the `show` option of the `v-tooltip` directive, but then I realized I didn't know how I'd also be able to specify the `boundariesElement` option from `Conversation.vue`.  I tried using the `Popover` component instead of the `v-tooltip` directive but I noticed the style didn't match and stopped there.

**Comment by marcoambrosini** [comment]
I'd say option 1 with placement "auto" is a way to go. Have you tried setting the hide delay to 0?

**Comment by carlcsaposs** [comment]
> I'd say option 1 with placement "auto" is a good way to go. Have you tried setting the hide delay to 0?

Sounds good; I'll PR that.  Regarding the delay, yes:
> I tried setting the delay to 0 but the shift was still present, just much shorter.

**Comment by marcoambrosini** [comment]
What about setting the whole `li` element as container?

**Comment by carlcsaposs** [comment]
> What about setting the whole `li` element as parent element?

As in, apply the tooltip to the `li` element?  If so, here's what it looks like:
![a](https://user-images.githubusercontent.com/97926121/171007034-3622ea64-783c-41a7-ad9b-543e2189ad4c.png)

It prevents the shifting issue, but I think it might mess up the accessibility tags (i.e. `aria-describedby`).

**Comment by marcoambrosini** [comment]
hmmm.. @juliushaertl do you have any suggestions here?

**Comment by nickvergessen** [comment]
From my POV this should be fixed in the Vue lib, otherwise every consumer of the lib has to manually do this?

**Comment by nickvergessen** [comment]
@Antreesy you fixed this lately, right?

**Comment by Antreesy** [comment]
> @Antreesy you fixed this lately, right?

We have a solution now with implementing a native title manually, but that's more a patch rather then a solution. Roughly speaking, issue can be closed. 

Last discussion was here:
https://github.com/nextcloud/nextcloud-vue/pull/3715
