### ISSUE TITLE
Final step of conversation creation doesn't focus

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7584]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. `+`
2. Enter a name
3. Tick "Allow guests"
4. Use keyboard tab to navigate to the next page
5. Tab through the user list and navigate to the next page

### Expected behaviour
The dialog is focused at the top

### Actual behaviour
Finish button is still focused (as it's the same button we just change the label) and pressing tab jumps to the message input in the background

**Comment by Antreesy** [comment]
Current focused element could be checked with `document.activeElement`
Fine soultion would be to watch for the number of current visible page in dialog, and focus appropriate elements with `$this.ref`

**Comment by DorraJaouad** [comment]
The current behavior aligns with the expected behavior as the dialog stays focused at the top and no jumping to the input occurs. This is solved @Antreesy  ? 

https://github.com/nextcloud/spreed/assets/84044328/54b2daf2-4a7c-406e-a820-1b54df2c8230

**Comment by Antreesy** [comment]
> The current behavior aligns with the expected behavior as the dialog stays focused at the top and no jumping to the input occurs

If you check in console `document.activeElement` at the last step, you'll see that it's a DOM element of NewMessage input (because we create a conversation and enter it, NewMessage considers it as change): https://github.com/nextcloud/spreed/blob/c0b1e2d7bf16209d6ea6d4084f026639bcfad4c2/src/components/NewMessage/NewMessage.vue#L379-L381

so we need to focus back to the modal elements automatically (to `Copy conversation link` button, for example)
