### ISSUE TITLE
Adjust to changes in Popover component

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7639]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

* Ref https://github.com/nextcloud/nextcloud-vue/pull/2600

**Comment by hanserasmus** [comment]
@nickvergessen is this proposed change to the popover to eliminate the issue where we cannot hover over the checkmark(s) in Talk messages in order to see if the message has been read by everyone? Don't want to open an issue if this is exactly what you are trying to fix. 

Example of a message written on one line only:

![image](https://user-images.githubusercontent.com/24249616/181915963-f59cd31c-fb01-4b61-9484-5c417c64ac26.png)

Example of 2 line message:

![image](https://user-images.githubusercontent.com/24249616/181915987-6be4391a-18e2-41bb-b189-23b4c43d2a28.png)

Multiline message grants capability of seeing read status:

![image](https://user-images.githubusercontent.com/24249616/181916076-eb883692-a4d9-40c2-a2b1-d472dd466ed8.png)

**Comment by nickvergessen** [comment]
No, that is not about it. Can you raise that as an individual issue?
