### ISSUE TITLE
Disabling and reenabling an Actions component yields a Vue warning

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7715]
```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "disabled"

found in

---> <ButtonVue>
       <VPopper>
         <VDropdown>
           <Popover>
             <Actions>
               <NewMessageForm> at src/components/NewMessageForm/NewMessageForm.vue
                 <ChatView> at src/components/ChatView.vue
                   <MainView> at src/views/MainView.vue
                     <AppContent>
                       <Content>
                         <App> at src/App.vue
                           <Root>
```

Only mutation should be:
https://github.com/nextcloud/nextcloud-vue/blob/71468d3a42bc0e53899e31e1df6fdfb093ec3840/src/components/Actions/Actions.vue#L836

**Comment by raimund-schluessler** [comment]
My guess is, that this:
https://github.com/nextcloud/spreed/blob/14b782f39306535ebcd1903b0a246542a7404404/src/components/NewMessageForm/NewMessageForm.vue#L293-L299
is not needed anymore at all, and is simply a leftover from when the `Actions` component had no `disabled` prop.
It wouldn't trigger any warning up to nc/vue 5.4, because `$refs.menuButton.disabled` didn't target a prop (`$refs.menuButton` was a simple HTML button and not a button component as it is with 6.0.0).
