### ISSUE TITLE
CSS blur filter seriously impacts performance in Chrome

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#7896]
Notice the sharp fps drop when the filter is active

https://user-images.githubusercontent.com/26852655/189666173-71eda72e-24c4-419d-8a43-2ae4ce7bb900.mov

**Comment by nickvergessen** [comment]
Cc @jancborchardt @nimishavijay we might have to drop the filter/transparency for the call view. Dropping FPS by 75% does not sound acceptable.

**Comment by marcoambrosini** [comment]
The same problem happens with the navigation. I think we should blur the image on the server and send it to the client, along with the regular one.

**Comment by danxuliu** [comment]
Despite the initial fears, after a lot of testing this may not be exactly the same issue that we had in the past with the blur filter for the [background of call participants](https://user-images.githubusercontent.com/26852655/83739955-865f1d00-a656-11ea-9e4a-20c04797ff8d.png), although it is difficult to say :-( Back in the day it was easily reproducible in Chromium (and Safari, which ultimately led to [completely disabling the blur](https://github.com/nextcloud/spreed/pull/4985), as [the work around developed for Chromium](https://github.com/nextcloud/spreed/pull/4678) could not be used in Safari), but fortunately this one seems much more restricted. That could be just a side effect of [GPU rasterization now being enabled by default on GNU/Linux](https://chromium.googlesource.com/chromium/src/gpu/+/0746f77293ddc5eaa7750c35e252363bc1dcb3ac), but the filter type probably plays a role too.

The video above was captured in a virtual machine where Chromium graphics features were either disabled or software only (as shown in `chrome://gpu`). However, when running Chromium in the host with GPU rasterization, compositing and OpenGL having blur or not does not _feel_ different. If GPU rasterization is disabled (which can be done in `chrome://flags`) again there is no difference between having blur or not; there is no lag in either case.

But there is also an interesting difference between the old blur and the current one: [the old blur](https://github.com/nextcloud/spreed/blob/9708a54b30f8475e60c40d80aa5ec88c26ad8abd/src/components/CallView/shared/VideoBackground.vue#L137) was used in a `filter` CSS property, while [the current one](https://github.com/nextcloud/spreed/blob/216577aa7745ca1f2af4d6d9cd612afcfe2c4aaf/src/components/CallView/CallView.vue#L681) is used in a `backdrop-filter` CSS property. The following examples (rename to `.html` rather than `.txt`) show the difference between them (the blur value is extremely large to emphasise the performance hit):
[test-blur.txt](https://github.com/nextcloud/spreed/files/9552467/test-blur.txt)
[test-blur-backdrop.txt](https://github.com/nextcloud/spreed/files/9552466/test-blur-backdrop.txt)

Chromium does not render again the DOM elements unless something changes. This can be checked in the frame rendering stats (Developer tools->Customize and control DevTools->More tools->Rendering) after opening the samples; if nothing changes in the page the stats are not updated. However, when hovering on the text its background is coloured, which causes a redraw and the stats are updated.

In the virtual machine both filter types cause lag; it happens even when updating an element that is not overlapping the element that has the blur (for example, the first paragraph in the `backdrop-filter` example). But on the host, on an older system from almost 20 years ago, and on a relatively recent laptop from 4 years ago, all without GPU rasterization, updating the text background when hovering it has lag if `filter` is used, but it does not if `backdrop-filter` is used. This can be checked by quickly moving the cursor over the text, entering an exiting it; this shows a much lower FPS when using `filter` than when using `backdrop-filter`. And if `filter` is disabled the FPS increase when doing it again.

It is also worth noting that testing an actual call with the `backdrop-filter` blur in the old system does not feel more laggy than without blur (it is far from snappy, but it does not feel worse, as it is the case in the virtual machine).

To sum up, from my tests:
- With GPU rasterization there is no noticeable performance hit
- Without GPU rasterization:
  - There is no noticeable performance hit when running Chromium in a real machine, even an old one, and using `backdrop-filter` (which is the property used now) rather than `filter` (the one that caused issues in the past)
  - There is a noticeable performance hit when running Chromium in a virtual machine, even if `backdrop-filter` is used (as shown in the video); it could be related to other hardware accelerated features not being available besides the GPU rasterization

However, there are also issues in Chromium bug tracker about [blur being slow with GPU rasterization rather than without it](https://bugs.chromium.org/p/chromium/issues/detail?id=941923) :shrug: (although I can not reproduce that). So it would be good to have more testing on this (with actual calls rather than the test code), preferably with low end devices, as the sample size right now is quite limited.

**Comment by joebnb** [comment]
still a problem
