### ISSUE TITLE
Quoting a message that expires does not show a quote

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7993]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Set up expiration
2. Post a message
3. Disable expiration (or take a good enough break so you can see it)
4. Quote the previous message
5. Wait for the message from **2** to expire
6. Check there is still a quote on 4

### Expected behaviour
Indicator that the quoted message expired, similar to when it was deleted

### Actual behaviour
No quote section visible

**Comment by SystemKeeper** [comment]
That’s also a problem in talk-ios. @Ivansss

**Comment by nickvergessen** [comment]
It's a problem on the api. Let's see

**Comment by SystemKeeper** [comment]
It's also a problem when we remove the message locally, because it expired. Then the message is removed from the tableView, but might still be visible as a quote. If the message is completely removed (from realm) and the cell is loaded again (scrolling away/leaving chat) the quote is also not visible anymore, so the indicator is also missing.
(independent from being a problem on the api)

**Comment by nickvergessen** [comment]
Okay, the API seems to be "correct" and 
https://github.com/nextcloud/spreed/blob/14e002a6d2f6d5dea45767c6ece4ff037ddee669/docs/chat.md#parent-data
is being returned.
