### ISSUE TITLE
Web UI: Ability to expand conversation pane

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/spreed#8033]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
As of now, it is not possible to horizontally expand/shrink the conversation pane. This is fine with 1-to-1 conversations as typically user names fit in the area, but it is likely to have public and group conversation with the title not fitting the area and ended with ...

Moreover hovering on the long title doesn't show the full title in a tooltip.

**Describe the solution you'd like**
I'd like to be able to expand / shrink the conversation so to see my conversations with the full title. 

**Describe alternatives you've considered**

**Additional context**
The same could be implemented for the right vertical bar.

**Comment by nickvergessen** [comment]
So one part to it is the immense padding which was added as a bug (in average 3-4 more characters would be displayed otherwise which can help already):
https://github.com/nextcloud/nextcloud-vue/issues/3287

Hover/tooltip is already requested in #7300 and also really useful.

General width adjustment of the left sidebar should be discussed here: https://github.com/nextcloud/nextcloud-vue/issues/1561
If we make the size draggable or something that should be done in the component directly.

So if you are fine with it, I would close this issue

**Comment by pmarini-nc** [comment]
Sure, you can close it. I was discussing it with @marcoambrosini, who may follow-up on the topic. Thanks!
