### ISSUE TITLE
Clarify if recording store should use HPB or SIP

### ISSUE THREAD

**Issue by vitormattos** [nextcloud/spreed#8521]
> The upload is done by the HPB, not the SIP bridge, right? @danxuliu 
> So I guess we need to use the `getSignalingSecret` here in the end.
> However that shows that the method is independent from "SIP" and should maybe have a neutral name and home (HelperService ?)

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/pull/8492#discussion_r1060114046_

**Comment by nickvergessen** [comment]
@danxuliu

**Comment by danxuliu** [comment]
Yes, the SIP bridge is unrelated to call recording. However, the upload will not be done by the signaling server either, but by the recording server. It will use the same pattern of including in the headers a random and its checksum hashed with a secret in order to validate the request, although the secret will be specific to the recording server. I have already modified the configuration to add that secret and I will push the changes along with the recording server.

But independently of that, yes, `SIPBridgeService::validateSIPBridgeRequest` should be renamed to something more generic/neutral, as the SIP bridge is not involved but also because [the `SignalingController` could be refactored to use that](https://github.com/nextcloud/spreed/blob/5f060687c8a0c77f1a61bf9a3462d4bfa4fe055f/lib/Controller/SignalingController.php#L433-L460) too (and this can be already changed [keeping the current code in the `RecordingController`](https://github.com/nextcloud/spreed/pull/8492/files/6f3a8e6b8d48727b160b37edd9b548c937e6e9e6#diff-bb5e688d438473d87c32cd4d2da5e623e2765be784e122f2b986f2d3cca07929R93-R95), even if the headers and the secret will be adjusted later).
