### ISSUE TITLE
Poll results shows dark avatars only on first opening

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8625]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a closed poll
2. Open the results

### Expected behaviour
If your system is in dark mode, the user avatars should be requested in dark mode as well

### Actual behaviour
First opening:
![image](https://user-images.githubusercontent.com/1580193/215501608-75c806d9-a8ac-4622-a0ce-516baee71bca.png)

Opening again:
![image](https://user-images.githubusercontent.com/1580193/215502005-8a025ad2-4de7-40ed-8dc1-8121e0a79133.png)

## Talk app

**Talk app version:** Master (@ 7dc878f1899d646c925ee5b073a93430cf3e40d5)

## Browser

**Operating system:** MacOS 13.2

**Browser name:** Safari & Chrome

**Browser version:** 16.3 & 109

**Comment by nickvergessen** [comment]
Basically means we are not using the avatar component

**Comment by SystemKeeper** [comment]
Not sure:

https://github.com/nextcloud/spreed/blob/c4e47dcb3d586c860e00b1f50ffa26b2f20d1778/src/components/MessagesList/MessagesGroup/Message/MessagePart/PollVotersDetails.vue#L27-L35

https://github.com/nextcloud/spreed/blob/c4e47dcb3d586c860e00b1f50ffa26b2f20d1778/src/components/AvatarWrapper/AvatarWrapperSmall.vue#L36-L44

or which component are you referring to?

**Comment by Antreesy** [comment]
Here are some research results:
- Avatar comes as image from server. Its color is defined by method `avatarUrlGenerator()` in [`NcAvatar.vue`](https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcAvatar/NcAvatar.vue)
Related PR: https://github.com/nextcloud/nextcloud-vue/pull/3119/files
- method `avatarUrlGenerator()` is called with method `loadAvatarUrl()`, which is called in `mounted` hook, but returns different result from the second attempt
- parameter `--background-invert-if-dark: invert(100%)` is defined by app theme (dark.css) and remains the same in process

So the conclusion is, result of `window.getComputedStyle()` call is [inconsistent due to different browsers and security reasons](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)
Changing the attribute from `this.$el` to `document.body` [in this place](https://github.com/nextcloud/nextcloud-vue/blob/10982969daa388aa3fb16fbf88b4055335016f7a/src/components/NcAvatar/NcAvatar.vue#L621) works, because `body` and its style aren't changing, unlike the unmounted and mounted again avatar

**Comment by SystemKeeper** [comment]
Nice analysis 👍 
These look similar to what you discovered: https://github.com/nextcloud/server/pull/36462
https://github.com/nextcloud/nextcloud-vue/pull/3707
