### ISSUE TITLE
Add a warning in the admin recording settings about post_max_size and upload_max_filesize

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8824]
After testing recordings for some minutes I ran into the following warning being logged:
```
Uploaded file might be larger than allowed by PHP settings 'upload_max_filesize' or 'post_max_size' 
```
https://github.com/nextcloud/spreed/blob/6533d77149c1d622e2f9ab710f2c0cd112d5e57d/lib/Service/RecordingService.php#L135-L140

That should:
1. Be logged as an error
2. Trigger a notification for the moderator so they know the recording will never appear and they need to reach out to the admin

**Comment by vitormattos** [comment]
@nickvergessen what will be the minimum values that we will use to show the warning when the values are greater than this minimum values?

Do you wish to put this minimum value using initial state at AdminSettings or using Capabilities->config? I think that using capabilities->config will be best because can be used by other clients.

I know that isn't possible for now, but would be good if the endpoint `/settings/ajax/checksetup` could be expanded with an event to make possible intercepted by apps to add our check setup items to be displayed at `Administration > Overview > Security & setup warnings`.

**Comment by nickvergessen** [comment]
> I think that using capabilities->config will be best because can be used by other clients.

Is not needed, we only show this in the admin settings. so initial state there is good enough

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/8846 referenced a wrong ticket, reopening
