### ISSUE TITLE
Clarification about who will be notified once a recording is available

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#8867]
Regarding this:
https://github.com/nextcloud/spreed/blob/3f7597826cd2745a4483f37931fec417384e347c/src/store/conversationsStore.js#L707

This will be displayed to the person who stops the recording. This can be anyone with moderation rights, but if I'm not mistaken, only the person who started the recording will be notified about the recording being available (because it's uploaded to that person).

Should we adjust the wording here? Is the person who started the recording available as a information somewhere?

**Comment by nickvergessen** [comment]
yeah I guess so.

The question is if the information is available in the frontend at that time and I fear the answer is "no".

**Comment by SystemKeeper** [comment]
In theory the one who starts the recording can leave at any time and join again or someone else stops the recording. So even if the information was available in the frontend, it probably wouldn't be useful in this case.

**Comment by nickvergessen** [comment]
> So even if the information was available in the frontend, it probably wouldn't be useful in this case.

I meant the "stop recording" request is not returning the information to the frontend who will be notified.
Actually it seems also the backend does not know as it's not keeping a record. So will only be the recording backend?

cc @danxuliu

**Comment by danxuliu** [comment]
The recording server keeps track of who will be the owner of the recording to send that user id when uploading the recording, so it would be trivial to also send the owner when the recording is stopped.

But... that would not solve the problem, because the message is currently shown when the request to stop the recording is sent to the Nextcloud server, and not when the Nextcloud server notifies the clients that the recording was stopped.

Independently of that we could just show `Call recording stopped` to any moderator that stops the recording and only the full message if the moderator that stopped the recording is also the one who started it, as `Call recording stopped. {XXX} will be notified once the recording is available` to tell a moderator that someone else will receive a notification seems a bit strange to me.

**Comment by vitormattos** [comment]
Hi @marcoambrosini and @nimishavijay 

What do you think about this question?

Now, the moderator that request to stop the recording, immediately when click to stop will send to Talk API a request to stop the recording and will see a notification with the message `Call recording stopped. You will be notified once the recording is available.`. The Talk API when receive the request to stop the recording, will send this to Recording Server to start or stop the recording.

After this action did by a moderator, all the participants will receive one of the following message at the conversation:
```
{actor} started the video recording
{actor} stopped the video recording
{actor} started the audio recording
{actor} stopped the audio recording
```

@SystemKeeper looking the flow, I think that now the message is ok.

I think that the point that @danxuliu touched is if is necessary to send the message `Call recording stopped. You will be notified once the recording is available.` to all moderators and not only to moderator that started the recording.

**Comment by nimishavijay** [comment]
Mentioning the name of who started/stopped the recording seems like a privacy issue because the person who started/stopped the recording might want to just keep it for themselves or as a log. The moderators who started or stopped the recording can get the message `Call recording stopped. You will be notified once the recording is available.` and all other participants (moderators or otherwise) can get the message `Call recording stopped`. cc @marcoambrosini also

**Comment by vitormattos** [comment]
TODO:

- [ ] Change the system message to don't display who started the recording.
