### ISSUE TITLE
Duplicate date header for the same date

### ISSUE THREAD

**Issue by provokateurin** [nextcloud/spreed#8880]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. User 1 sends message
2. User 2 opens chat and marks message as read, leaves again
3. User 1 sends another message
4. User 2 opens chat again and the date header is duplicated

### Expected behaviour
Only a single date header for a single date

### Actual behaviour
Duplicated date header for the same date

## Talk app

**Talk app version:** c.nc.c

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** Arch

**Browser name:** Firefox

**Browser version:** 110.0

![image](https://user-images.githubusercontent.com/26026535/221781412-c9ff9125-cbdf-4e34-8f46-67af104211ca.png)

**Comment by provokateurin** [comment]
Actually the duplicate date header stays even after reading the chat and re-opening it etc.

**Comment by SystemKeeper** [comment]
I saw that with Ivan the other day as well. Back then it looked like it depends on new message blocks being loaded. So if you send a message in that conversation, reload the page and scroll up, the date indicator would be at different position. Could you check that?

I think we don't remove a date indicator for the same date if another is being added due to a new block being loaded, but we add one if a date change is detected here
https://github.com/nextcloud/spreed/blob/ef573c75b0d593f458291e11ea9fa0faad88d6a3/src/components/MessagesList/MessagesList.vue#L209

**Comment by provokateurin** [comment]
After sending another message and reloading it's completely gone.

**Comment by SystemKeeper** [comment]
Then probably it was exactly the message block boundary... 

Initial:
```
---
-> Date indicator 2023-02-01
50 Messages from 2023-02-01
---
```

Now after scrolling up the you load 25 messages from 2023-02-01 and 25 messages from 2023-01-31, you end up with this:
```
---
25 Messages from 2023-01-31
-> Date indicator 2023-02-01 (because a date change is detected)
25 Messages from 2023-02-01
-> Date indicator 2023-02-01
50 Messages from 2023-02-01
---
```
