### ISSUE TITLE
Pasting images sometimes are added twice

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9004]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Copy an image
2. Paste it into a conversation

### Expected behaviour
The image should be shown once in the file upload preview modal

### Actual behaviour
Sometimes the same image is shown twice in the upload preview modal and will also be uploaded/posted twice. Doesn't matter if you use the context menu or CMD+V/CTRL+V.

https://user-images.githubusercontent.com/1580193/223829229-f938b674-8cc4-47ef-8ca5-a791ee605039.mov

## Talk app

**Talk app version:** c.nc.c

## Browser

**Operating system:** MacOS Ventura 13.2

**Browser name:** Safari and Chrome

**Browser version:** 16.3 and 110

**Comment by nickvergessen** [comment]
Can not reproduce here :(
Does it happen on other pages as well?

**Comment by nickvergessen** [comment]
However also on FF I see the temporarymessage twice in the console:
![grafik](https://user-images.githubusercontent.com/213943/224024796-28d696f9-960c-4188-a402-8af47075e688.png)

It seems like the `@paste="handlePastedFiles"` is triggered twice by `NcRichContenteditable`

**Comment by Antreesy** [comment]
`NcRichContenteditable` emits paste event to the `NewMessageForm`, which we're handling in the Talk app
![image](https://user-images.githubusercontent.com/93392545/224084290-bb39be6e-e70e-4f47-b54d-1ec2f47309c6.png)

The check on the screenshot above doesn't work for us, because both `clipboardData.files` and `clipboardData.items` arrays are empty, so I guess, we're handling them twice, by each component
