### ISSUE TITLE
Personal and 3rd-party messages divided by sides of chat area

### ISSUE THREAD

**Issue by lesykm** [nextcloud/spreed#902]
Like it is done in most of modern messages, like:
https://static.makeuseof.com/wp-content/uploads/2015/01/whatsapp-web-everything-670x335.jpg
Should be pretty simple fix, will try to poke css this weekend if will find time.
Example: ![chat_example](https://static.makeuseof.com/wp-content/uploads/2015/01/whatsapp-web-everything-670x335.jpg)

**Comment by nickvergessen** [comment]
@jancborchardt can you make a suggestion?
mirroring the layout feels awkward because the time is then on the wrong side for your own messages?

**Comment by nickvergessen** [comment]
> ![bildschirmfoto von 2018-07-17 12-11-43](https://user-images.githubusercontent.com/213943/42811515-14165268-89bb-11e8-941d-b5ee6ddfc38a.png)

My suggestion would be to skip your own name

**Comment by jancborchardt** [comment]
I’m not entirely sure about this. Slack for example doesn’t do any of the right-alignment, and neither does Wire: https://wire.com/en/

On mobile it is nice, but on desktop it doesn’t particularly add reading flow, and we would need to add some max-width and probably center everything.

**Comment by nickvergessen** [comment]
Yeah I noticed Slack to, and it was the first comment together with IRC.
But e.g. Telegram and Whatsapp do it also on the desktop.
I think it would help with reading and searching for stuff, because you can easily spot where you interacted in the communication

**Comment by jancborchardt** [comment]
Another idea would be to add a blue bar to the left of your own messages, as we do for the active entry in the left navigation?

That also serves as an indicator and does not change the whole layout.

**Comment by nickvergessen** [comment]
Sample in main view:
> ![bildschirmfoto von 2018-07-18 10-57-09](https://user-images.githubusercontent.com/213943/42871079-c42c1016-8a79-11e8-834e-a1898a7786d5.png)


Sample in sidebar:
> ![bildschirmfoto von 2018-07-18 10-59-29](https://user-images.githubusercontent.com/213943/42871082-c5884ad8-8a79-11e8-837d-1b7ac956f895.png)

**Comment by nickvergessen** [comment]
If you want to play around with it a bit:
```diff
diff --git a/css/comments.scss b/css/comments.scss
index 52ef5eee..e067ed39 100644
--- a/css/comments.scss
+++ b/css/comments.scss
@@ -257,6 +257,18 @@ body:not(#body-public) #commentsTabView .comment .authorRow:not(.currentUser):no
        color: $color-primary-text;
 }
 
+#app-content-wrapper #commentsTabView .comment.currentUser {
+       box-shadow: inset 4px 0 $color-primary;
+       margin-left: -40px;
+       padding-left: 36px;
+}
+
+#app-sidebar-wrapper #commentsTabView .comment.currentUser {
+       box-shadow: inset 4px 0 $color-primary;
+       margin-left: -10px;
+       padding-left: 6px;
+}
+
 body:not(#body-public) #commentsTabView .comment:not(.newCommentRow) .message .mention-user:not(.current-user) {
        cursor: pointer;
 }
diff --git a/js/views/chatview.js b/js/views/chatview.js
index b9b3f5e9..1f481a6e 100644
--- a/js/views/chatview.js
+++ b/js/views/chatview.js
@@ -52,7 +52,7 @@
                '</div>';
 
        var COMMENT_TEMPLATE =
-               '<li class="comment" data-id="{{id}}">' +
+               '<li class="comment{{#if isUserAuthor}} currentUser{{/if}}" data-id="{{id}}">' +
                '    <div class="authorRow{{#if isUserAuthor}} currentUser{{/if}}{{#if isGuest}} guestUser{{/if}}">' +
                '        <div class="avatar" data-user-id="{{actorId}}" data-displayname="{{actorDisplayName}}"> </div>' +
                '        <div class="author">{{actorDisplayName}}</div>' +
```

**Comment by nickvergessen** [comment]
so, to do or not to do?
cc @jancborchardt @jenniferpiperek

**Comment by jenniferpiperek** [comment]
I see this could be a problem mostly in group conversations, don't this?

I agree with @jancborchardt, that the left-right alignment does not necessarily increase the reading flow. For desktop I would opt for every message to be left-aligned :)

As far as I can remember you told me that there is a background color generated for each person who does not set a photo for their avatar. What do you think about using this color also for the "name label"? People who have a photo-avatar should also have a coloured "name label".

I think of something like this.

> <img width="730" alt="Screenshot 2019-04-11 at 12 44 27" src="https://user-images.githubusercontent.com/25012486/55951817-71584b00-5c58-11e9-8a91-597f75d4ad4a.png">

Also Telegram, Whats App, ... do this for group chats. If your name+avatar is not enough an indicator for you, maybe the color could help you spotting your sent messages. 

Since the blue indicator is used for highlighting the active tab, I think this "style" should be used in other cases also for highlighting something. We could use it as an indicator for a certain message, like a message someone replied to.
(Example from Telegram)

> <img width="505" alt="Screenshot 2019-04-11 at 12 53 41" src="https://user-images.githubusercontent.com/25012486/55952161-31459800-5c59-11e9-9d9e-60d7eda39a8d.png">

What do you think?

**Comment by mario** [comment]
@jenniferpiperek the problem seems to be that in your screen you color the names even if the avatar is set, and in this case (like you rightfully pointed out) we don't have a color? 

(It's a whole other can of worms that some people are color blind to a degree).

In addition, what do we do with mobile? Android currently has left/right separation with bubbles, while the iOS mimics the web interface completely.

Thanks for your insights btw! :)

**Comment by nickvergessen** [comment]
> In addition, what do we do with mobile? Android currently has left/right separation with bubbles, while the iOS mimics the web interface completely.

When we go for this, we should do it on all platforms.
IOS is not a matter here, it's because Ivan used a lib for the layout and that is the default and afterwards there were more important things to do.

**Comment by jenniferpiperek** [comment]
> @jenniferpiperek the problem seems to be that in your screen you color the names even if the avatar is set, and in this case (like you rightfully pointed out) we don't have a color?

Isn't it generated from the name? In that case it should also work for people who provided a photo. However thanks for mention how it would work for people with color blindness. I agree that they might not differentiate. I came up with that suggestion because there is still the name of the person shown. But yeah, if colors are used they should be optimized (e.g. in contrast) to make sure the text is readable.

> As for left-only on desktop, I think we all agreed already :)

@nickvergessen Is this issue now about how to indicate your own messages? I don't think I quite understand. Can you please explain what you need :)

**Comment by nickvergessen** [comment]
Closing this as we don't want to split sides or have colors

**Comment by Fuseteam** [comment]
wait, why not? it may noy help with readflow but does help with scroll searching (scrolling up for something you know you sent but don't recall enough to search with text)

**Comment by ShGKme** [comment]
@Fuseteam Split messages UI is implemented already and will be available in 26 Winter.

**Comment by Fuseteam** [comment]
oh that's great! looking forward to it
