### ISSUE TITLE
Notifications don't behave as expected & need to join rooms

### ISSUE THREAD

**Issue by mario** [nextcloud/spreed#920]
Hello,

first of all, apologies for mixing things and writing a longer issue, but I feel it's needed.

1) What's the goal of joining/leaving rooms? The user should ALWAYS belong to the room he's participant in. Simple as that. Also I cannot guarantee that I'll be able to leave call or a room at the appropriate time OR ever. This means notifications stop working.
2) If you join a room to chat, you will not receive ANY more notifications for this room. That is silly considering you might get a call in the same room :(

**Comment by Ivansss** [comment]
> 
> 1. What's the goal of joining/leaving rooms? The user should ALWAYS belong to the room he's participant in. Simple as that. Also I cannot guarantee that I'll be able to leave call or a room at the appropriate time OR ever. This means notifications stop working.

The goal is to show your status to other people in that room.
Whenever you join a room, other people can see that you are there (Your name is no longer half-transparent in the right side bar).

> 2. If you join a room to chat, you will not receive ANY more notifications for this room. That is silly considering you might get a call in the same room :(

That should not be the case. Even if you are in a room, you should receive a notification if a call starts in that room.

**Comment by mario** [comment]
Join a chat via mobile app. Go to web app on your desktop as a different user. Try calling the user on the mobile app ;)

This is kindof a critical bug :(

**Comment by Ivansss** [comment]
You are right, notifications are only sent to users that are not in the room.
But I won't consider it a bug.

When using the web app, you can see in the participants tab that someone has joined a call.
Once system messages are added, you will see in the chat that someone has started a call, so notifications won't be necessary for any platform.

Since we get all the information, we should think about how to show that in mobile apps.
Maybe adding a green dot next to phone and camera icons when there is an ongoing call in that room?

![img_e0152](https://user-images.githubusercontent.com/4638605/40664642-ae7d1df4-635b-11e8-979e-8f786951440f.JPG)

**Comment by mario** [comment]
It is a bug. While I agree with you that we should show something next to the camera/phone icon, the issue is that, like I said before, I CANNOT guarantee that I'll be able to leave rooms before app crashes or something unexpected happens.

Notifications are necessary. Wherever you show them or not is up to the app, but we need to send them.
