### ISSUE TITLE
Own messages sometimes lead to unread marker in conversation list

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/spreed#9206]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Follow-up to https://github.com/nextcloud/spreed/issues/8862

## Steps to reproduce
1. Be in a conversation
2. Write messages

### Expected behaviour
My own messages should not lead to a unread indicator.

### Actual behaviour

https://user-images.githubusercontent.com/1580193/228540367-70078f8c-53a3-465a-ba7d-c22fbd253258.mov

It's not always reproducible, sometimes it's just working fine...

## Talk app

**Talk app version:** 16.0.1 on c.nc.c

## Browser

**Operating system:** MacOS

**Browser name:** Chrome

**Browser version:** 111

**Comment by SystemKeeper** [comment]
> #9134?

Ah, no sorry. Mentioned it in the other comment, it’s not related to reactions, just plain messages. Forgot to add it here ..

**Comment by nickvergessen** [comment]
So after around 2 hours of debugging we found the problem and with a sleep in the correct place can reproduce it consistently.

* The sleep has to go before:
https://github.com/nextcloud/spreed/blob/5ac5d00e2d64f580aadc3257d166c1df4c904313/lib/Controller/ChatController.php#L182
* HPB helps in reproducing
* The bug appears more often since the recent performance update to only return changed rooms

### Bug

The actual issue is that your room list is refreshed between the moment your posted message was written to the database and then your read marker is updated with this message in the database.
So the room list update already knows about your new message ID, but still loaded your old read marker ID.

### Cover

The bug was covered before, by the fact that your roomlist updated all rooms all the time. So whenever another room list refresh was triggered because of any activity in any other room, the readmarker was fixed for this conversation as well, but now **this conversation** is not part of the response anymore because it did not update since the last time you requested the room list
