### ISSUE TITLE
Translate chat messages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9273]
- Since Nextcloud 26 a core API to translate strings is available in the server: https://github.com/nextcloud/server/blob/a0ecc37d036ace7bd32675f89b046bf0bff1fe89/core/Controller/TranslationApiController.php#L37
  - API docs at https://github.com/nextcloud/documentation/pull/10047
  - Capability at https://github.com/nextcloud/spreed/pull/9321
- There should be a … Message actions to translate messages.
- A modal opens translating the message to the currently selected user language and allowing in a dropdown to translate to other languages

---

- [ ] Android https://github.com/nextcloud/talk-android/issues/2931
- [x] iOS https://github.com/nextcloud/talk-ios/issues/1185
- [x] Web https://github.com/nextcloud/spreed/issues/9528

**Comment by nickvergessen** [comment]
- API docs at https://github.com/nextcloud/documentation/pull/10047
  - Capability at https://github.com/nextcloud/spreed/pull/9321

**Comment by jancborchardt** [comment]
> A modal opens translating the message to the currently selected user language and allowing in a dropdown to translate to other languages

This sounds a bit complicated – I would rather go with how Instagram and Twitter do it and have a simple "Translate this message" action which only translates it to your language and places it below the original.
(Also talked about with @AndyScherzinger 

We could of course have a modal to translate to other languages too, but that should be a separate second step. Otherwise it’s basically having full DeepL/Gtranslate app in there where you still need to manually do everything → instead of just simply clicking a button.

**Comment by AndyScherzinger** [comment]
I think putting it in the 3dot menu on web or the long-press on mobile would be fine since showing it directly would mean we need to process all messages upfront to detect their original language to then decide when to show the translations action (as in show it when the language is not the one of the device). So putting it in the menu would be a good start.

**Comment by jancborchardt** [comment]
@nickvergessen thanks for the explanation – ok then I’m good with a modal. Could be the same dialog as in Text.
