### ISSUE TITLE
Attachments folder for the other person in a chat is not used, when uploading images / files via "upload from device" on Android app

### ISSUE THREAD

**Issue by nousernameavailableanymore** [nextcloud/spreed#9381]
Issue #8484 still occurs with version 25.0.6.
Nothing changed except the version.

In addition to the information provided already in the previous bug report: the target that is set as "Attachment folder" in Talk is located on a Network share that is mounted on the source OS and then added as "local" external storage.
Maybe that helps to reproduce.

**Comment by nickvergessen** [comment]
Yeah that might be the missing bit and I'm not sure that is something we can fix, as for our so there is no way that we can influence the order of mounting the mountpoints and basically for you the mount point is missing because the parent is missing sand so it falls back to the root

**Comment by nousernameavailableanymore** [comment]
> basically for you the mount point is missing because the parent is missing sand so it falls back to the root

I dont understand. What does that mean?
The network share is successfully mounted as a folder in the source OS.
This folder is then mounted as an external share of type "local".

Which part is not supported / causing the issue?
Is there a workaround?
Is there a way to fix this?

This used to work fine for several years and just broke in one of the Talk updates.

**Comment by nickvergessen** [comment]
> This folder is then mounted as an external share of type "local".

This is the problem I think.

So there is a mount point and we later on try to add the mount points of the Talk shares on to it. But since there is already a mount point on that path I guess it moves to a different path.

> Is there a workaround?
> Is there a way to fix this?

My easiest suggestion would be:
Don't use a "local storage" mount point for your Talk/ folder.

> This used to work fine for several years and just broke in one of the Talk updates.

That would be a complete surprise as we didn't touch that code in years, but maybe the underlying Nextcloud server code changed.

**Comment by nickvergessen** [comment]
Closing as per above
