### ISSUE TITLE
Viewer overlay doesn't support screensharing

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/spreed#9445]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce

1. Start a call with another active participant
2. Start screen sharing from any:
   - another participant
   - youself
3. Open a file in the viewer

### Expected behaviour

There is a screen sharing in the viewer overlay

### Actual behaviour

It is not

**Comment by Antreesy** [comment]
While doing that, now the confusing text is shown, `waiting for X to join the call`, while the participant is still there, just a peer from his screensharing is not passed to the overlay

**Comment by nickvergessen** [comment]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

Ref https://github.com/nextcloud/spreed/issues/9445

## Steps to reproduce
1. Be 2 people in the call
2. User A shares a document
3. User A shares their screen
4. User B opens the document

### Expected behaviour
Mini preview shows the screenshare or other person

### Actual behaviour
Mini preview shows "Waiting for X to join the call"
![image](https://github.com/nextcloud/spreed/assets/213943/94728774-75a2-4c2e-aaf0-aadab3df76c1)


## Talk app

**Talk app version:** 17.0.3

**Comment by nickvergessen** [comment]
@DorraJaouad was this touched/solved by your work?

**Comment by DorraJaouad** [comment]
No, the `ViewerOverlayCallView` is a different component from `CallView` component . It is lacking `Screen` components for both local model and the promoted model.
