### ISSUE TITLE
Echo during screen sharing with system sound

### ISSUE THREAD

**Issue by ElFDA** [nextcloud/spreed#9585]
Hello,
when I share the screen by enabling system sounds the viewers hear their voices when they speak, we have done many tests and it is not a problem with the return of the speakers 
is it a bug or is there some option to enable?
The configuration is:
Nextloud version: 25.0.6
Talk version: 15.0.5
Custom STUN and TURN server

**Comment by nickvergessen** [comment]
Please use the proper issue template to provide us with the required information:
https://github.com/nextcloud/spreed/issues/new?assignees=&labels=0.+Needs+triage%2C+bug&projects=&template=bug_report.md

Also please include how you screenshare with system sound, since we are not aware how that would work.
