### ISSUE TITLE
Media settings sometimes reset to a wrong microphone

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9902]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Have a webcam with a microphone and additionally a headset
2. Join a call

### Expected behaviour
Headset is used like you did the last times

### Actual behaviour
Sometimes it selects the webcam mic instead and you have to repick to the headset instead.

**Comment by nickvergessen** [comment]
Snapshot of data to compare next week:
Labels | IDs (after explicitly selecting airpods)
---|---
<img width="501" alt="Screenshot 2023-07-20 at 15 19 19" src="https://github.com/nextcloud/spreed/assets/213943/dac5a3a5-2e57-40f6-8cc6-26d96ae12c4d"> | <img width="811" alt="Screenshot 2023-07-20 at 15 24 29" src="https://github.com/nextcloud/spreed/assets/213943/5c78c969-2613-4968-99d5-1a6c5d582d6b">

**Comment by DorraJaouad** [comment]
As I checked the [MediaDeviceManager ](https://github.com/nextcloud/spreed/blob/master/src/utils/webrtc/MediaDevicesManager.js#L198-L204), there is a fallback to set the default or first audio stream if the current device Id was not found. Did you see a console log 
`'Could not find previous audio device, falling back to default/first device in the list'` ?

I couldn't reproduce it though.

**Comment by nickvergessen** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MediaDeviceInfo also seems to list a "groupId" maybe we can check that and see if it is helpful.

Above are some screenshots of devices from colleagues:

C | Audio | Video | OS Audio
---|---|---|---
Jan | ![grafik](https://github.com/nextcloud/spreed/assets/213943/b6937694-930c-4e81-8588-586eb1e375f7) | ![grafik](https://github.com/nextcloud/spreed/assets/213943/666b24f1-932e-4004-be53-fe7d5fa515dd) | ![grafik](https://github.com/nextcloud/spreed/assets/213943/1ecbe6a2-b1b3-4a5d-b74c-a9dea32e6aef)
Andy | ![grafik](https://github.com/nextcloud/spreed/assets/213943/9563b660-f064-49b4-abdf-0ae5710c2092) | ![grafik](https://github.com/nextcloud/spreed/assets/213943/397fe4b8-b4e0-4eff-ac17-020f5ae1cf6e)
me | ![Bildschirmfoto vom 2023-12-19 11-57-28](https://github.com/nextcloud/spreed/assets/213943/fbeda5f2-0156-40f4-8a11-b692d7311895) | ![Bildschirmfoto vom 2023-12-19 11-57-36](https://github.com/nextcloud/spreed/assets/213943/8f1ffb4b-b99a-4c0c-aa0d-10e25ae1b180) | ![Bildschirmfoto vom 2023-12-19 11-57-59](https://github.com/nextcloud/spreed/assets/213943/05199972-594a-4d84-b189-5fc0cbc595ad)

**Comment by DorraJaouad** [comment]
This is how audio media streams are handled for now:

* If a user selects an audio input device, it is stored in browser and will be selected for future calls.
* If the stored device is not found ( either different browser or the device was removed from peripherals), it falls back to default device (first on the list or `deviceId === default`). 

Even when you plug the headset again, it should reset to it because its id is still stored in browser storage unless you selected other device intentionally before plugging it and another id will be stored. So if you remove your headset and don't select any other device ( default is picked automatically) and then add your headset again, it will reset correctly.

![image](https://github.com/nextcloud/spreed/assets/84044328/8b3e1c8f-7156-459e-b0d0-e2e8ca9597ef)
